### ISSUE TITLE
Use string instead of integer to be account ID in config.json.demo

### ISSUE THREAD

**Issue by ccao93** [duo-labs/cloudmapper#10]
Suggest to change account id to be string instead of integer, because some account ID may start with 0, already tested, pyjq can process it properly.

**Comment by 0xdabbad00** [comment]
Looks like you can just wrap your account ID in quotes in the config file.  I've updated the demo config file to reflect this just now: https://github.com/duo-labs/cloudmapper/commit/48a2aca79182dc1e71245cfb983e4929a29fe1e8
