### ISSUE TITLE
Not seeing any ELBv2 instances on map

### ISSUE THREAD

**Issue by tnwhitwell** [duo-labs/cloudmapper#102]
Unsure if I'm just missing something / this hasn't been implemented yet, but i'm not seeing any load balancers at all on the map, meaning there are some stranded vpcs with seemingly no ingress. Has this been implemented yet, or am I just being dense?

**Comment by 0xdabbad00** [comment]
ELBv2's should work.  I might have broken something recently in my code pushes this past week. I'll check this weekend.

**Comment by tnwhitwell** [comment]
They are listed in the JSON files generated by `prepare`, but not coming up in the map itself. i haven't had enough time to look over the code yet, or I'd submit a PR, but thanks for taking a look!

**Comment by 0xdabbad00** [comment]
Fixed in https://github.com/duo-labs/cloudmapper/pull/104
