### ISSUE TITLE
Enforce use of Python3

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#107]
I've been using Python 2.7.  Periodically issues come up due to people using Python 3.  I need to make sure everything works with Python 3 and enforce it's use somehow.

**Comment by 0xdabbad00** [comment]
Updated to Python 3 in #113 . I'm not sure how to enforce as I think if Python 2 is attempted things might just error.

**Comment by riskynacho** [comment]
You need to update the readme.md to include installing python3 packages, as it is right now on RHEL & Debian based systems, it will install python version 2. 

The python dev packages which provide the python binary dependancy on RHEL is `python34-devel` and Debian, `python3-dev`

**Comment by 0xdabbad00** [comment]
Thank you! I've made updates with regard to your comments just now in https://github.com/duo-labs/cloudmapper/pull/118
