### ISSUE TITLE
White Blank Screen during serve

### ISSUE THREAD

**Issue by jkonkol** [duo-labs/cloudmapper#12]
After successful prepare step I ran:

python cloudmapper.py serve --public

When I go to the web page I can see the toolbar at the top and there is a blue progress bar that goes left to right, but it never makes it all the way to the right.

Here are the messages in the console during the page view (notice the code 404 message File not found) :

173.23.49.44 - - [20/Feb/2018 18:57:30] "GET / HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/nprogress.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/jquery.qtip.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/cytoscape.js-panzoom.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/cytoscape.js-navigator.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/font-awesome-4.7.0/css/font-awesome.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/akkordion.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/cloudmap.css HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/nprogress.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape.min.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/jquery.qtip.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/jquery.min.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-cose-bilkent.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-grid-guide.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /css/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-qtip.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-panzoom.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-undo-redo.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-view-utilities.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-expand-collapse.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:30] "GET /js/cytoscape-navigator.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/cytoscape-autopan-on-drag.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/FileSaver.min.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/circular-json.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/mousetrap.min.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/akkordion.min.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/nodeInfo.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /js/cloudmap.js HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] code 404, message File not found
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /data.json HTTP/1.1" 404 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /favicon.ico HTTP/1.1" 200 -
173.23.49.44 - - [20/Feb/2018 18:57:31] "GET /style.json HTTP/1.1" 200 -

**Comment by 0xdabbad00** [comment]
The `data.json` file is created during the `prepare` step, so make sure you run that first.  I should show an error though if that file isn't found, so I'll leave this open until I add some error handling code to account for that and better inform the user.

**Comment by 0xdabbad00** [comment]
@jkonkol I just saw you said you did successfully run prepare.  Can you double-check that it generated the `data.json` file?

**Comment by jkonkol** [comment]
I had logged off of my SSH session and forgot to run the virtualenv step again.  Once I did that the graph now renders as designed.
