### ISSUE TITLE
Network visualization: Filter by subnets

### ISSUE THREAD

**Issue by evman94** [duo-labs/cloudmapper#123]
It would be great to have a flag that enables to filter the prepare command output w.r.t. to the subnet(s) just like VPC.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
