### ISSUE TITLE
Feature: Per-VPC/Subnet Network Connections (Arrows)

### ISSUE THREAD

**Issue by j4v** [duo-labs/cloudmapper#125]
Currently network connections are displayed per-host: when a host (e.g. an EC2 instance) can communicate with another host (e.g. through a permissive SG rule), then an arrow goes from one host to the other.

The issue with this is that for accounts with a lot of hosts, we end up with hundreds of connections/arrows, often due to *one* SG rule (i.e. if you have 2 VPCs with 1 subnet each and each of these subnets has hundreds of EC2 instances, if a SG rule allows one subnet to access the other then each pair of EC2 instances will have an arrow).

Would it be possible instead that the arrow be between the VPC/subnet "square" instead of each host? This would:
- Better represent the network configuration
- Ensure that the graphs are readable.

**Comment by 0xdabbad00** [comment]
Thank you.  I think I need to create some sort of maximum and minimum granularity settings, so that you can filter in on only the nodes inside a subnet, or as this issue requests, to be able to only show subnets as the minimum granularity.

**Comment by j4v** [comment]
For example, this is what I'm seeing for an account with a lot of hosts in a few VPCs/subnets:

![sc_2018-07-20_12h31m23s](https://user-images.githubusercontent.com/4206926/42998248-d3d20196-8c19-11e8-827f-7f835ec972c0.jpg)

All of the links are because of just a few SG rules allowing traffic between subnets. In this case it would be beneficial if I could just see a link between VPCs/subnets.

**Comment by 0xdabbad00** [comment]
Yikes, I'm surprised that even displayed.  I'm focused on some other projects right now, but this feature is high on my todo list for this project.

**Comment by j4v** [comment]
It _is_ quite slow in the browser, but with some patience and hiding elements it gets the job done. Once I can download the image I can analyse it just fine.

Thanks a bunch for this tool, it is really invaluable when assessing large accounts (that screenshot isn't even all of it).

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
