### ISSUE TITLE
Ensure collapsed ASGs put a node in each AZ where appropriate

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#137]
Autoscaling groups are condensed to a single node by default.  Currently this works as a winner take all approach, so even if your ASG scales across multiple AZs, only one node will be shown.  I should ensure that for this case, that an ASG node is shown in each AZ.

**Comment by 0xdabbad00** [comment]
Based on the issue #131 which identified two fixes needed, one of which was fixed for the immediate issue raised there.

**Comment by yannvanhalewyn** [comment]
FYI, probably not the best way but this commit: https://github.com/duo-labs/cloudmapper/pull/135/commits/93c0bcf50f7c0c4e5b0ecf7e0b236c8be0203e68 (reverted) makes this happen.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
