### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by gdahlm** [duo-labs/cloudmapper#14]
With only 2 years left for python 2.7 and with many upstream modules dropping new feature support for 2.7 soon this should support python 3.5+

There is no contributor guide, but I will volunteer for this task if you can provide some style guidelines.

**Comment by gdahlm** [comment]
I created a pull request which seems to work fine.

https://github.com/duo-labs/cloudmapper/pull/18

**Comment by 0xdabbad00** [comment]
Thank you @gdahlm!
