### ISSUE TITLE
not checking for an None object

### ISSUE THREAD

**Issue by ms4720** [duo-labs/cloudmapper#161]
I have no db snapshots, or dbs, in this account.  I will try to send a pull request soon to fix this.  
```
  File "/Users/marc.spitzer/projects/github.com/dou-labs/cloudmapper/commands/audit.py", line 210, in audit_rds_snapshots
    for snapshot in json_blob.get('DBSnapshots', []):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by 0xdabbad00** [comment]
I've run the `audit` command in accounts without any databases or snapshots and not experienced this issue.  Try doing `cat account_data/YOUR_ACCOUNT/*/rds-describe-db-snapshots.json` and see if anything interesting shows up.  Each of those files should contain:
```

**Comment by 0xdabbad00** [comment]
{
    "DBSnapshots": []
}
```
Perhaps that file is missing?  If so, perhaps you had upgraded the code without running `collect` again?  Unfortunately some of the file naming has changed.

**Comment by ms4720** [comment]
```
ython3 cloudmapper.py collect
* Getting region names
[...]
* Getting rds:describe-db-instances info
* Getting rds:describe-db-snapshots info
* Getting rds:describe-db-snapshot-attributes info
[...]
(venv)XXX$ cd account-data/default/
ap-northeast-1/ ap-south-1/     ap-southeast-2/ eu-central-1/   eu-west-2/      sa-east-1/      us-east-2/      us-west-2/
ap-northeast-2/ ap-southeast-1/ ca-central-1/   eu-west-1/      eu-west-3/      us-east-1/      us-west-1/
(venv)XXX$ cd account-data/default/ap-northeast-1
(venv) $ cat  rds-describe-db-snapshots.json
(venv) $ nl  rds-describe-db-snapshots.json
     1	null
```

I ran the command again and same result, here is the version I am running:

```

commit 1d9331a55defa46522bcfa895b6cc8d6f36a572a (HEAD -> master, origin/master, origin/HEAD)
Merge: 71ed2c1 c225fbc
Author: Scott Piper <0xdabbad00@users.noreply.github.com>
Date:   Mon Aug 6 13:42:42 2018 -0600

    Merge pull request #159 from 0xdabbad00/apigateway_mapping

    Map API gateway URLs

```

**Comment by ms4720** [comment]
this might help:

-  aws-cli/1.15.70 Python/3.7.0 Darwin/16.7.0 botocore/1.10.69
- macos 10.12.6

**Comment by 0xdabbad00** [comment]
Another possibility, maybe your user doesn't have privileges to call RDS:describe-db-snapshots ?

**Comment by ms4720** [comment]
I will check, I followed the install guide( or I thought I did)

**Comment by ms4720** [comment]
the account I am using has a group set up with the following in it:

arn:aws:iam::aws:policy/SecurityAudit
arn:aws:iam::aws:policy/job-function/ViewOnlyAccess

it is not the only group on the account

**Comment by 0xdabbad00** [comment]
Those should work for this assuming something else isn't giving it a Deny somewhere.  At this point, I need to add more error checking code to CloudMapper, both on the `audit` command and on the `collect` command.

As a short-term work-around you could just comment out the call to the function to check the RDS snapshots or put some simple error checking there to say:

```
if json_blob is None:
  return
```

**Comment by 0xdabbad00** [comment]
I've added #164 for now

**Comment by 0xdabbad00** [comment]
Closing due to staleness
