### ISSUE TITLE
Add error handling on `collect`

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#164]
If the collect call encounters problems, such as an `Access Denied` it should bail, and provide a way for the user to power through Access Denieds.

**Comment by ms4720** [comment]
With a warning message

**Comment by 0xdabbad00** [comment]
I need to be mindful with this that other commands assume `collect` worked successfully, so if they don't have access to the data they need, they may fail or otherwise work incorrectly.

**Comment by 0xdabbad00** [comment]
Currently, when `collect` API calls fail, it prints out info at the end about which calls failed.  I think that's the best I can do for this.  The expectation is that CloudMapper has been given all the privileges it need to run `collect`.  Dealing with cases where that is not true is outside of the scope of this project.
