### ISSUE TITLE
MacOS build instructions still accurate?

### ISSUE THREAD

**Issue by mikerj1** [duo-labs/cloudmapper#184]
Building on MacOS results in the below error.  Build attempts with clang fail as well.  Are there new steps or dependencies that need to be added to the build instructions?  Thanks

creating build/temp.macosx-10.13-x86_64-3.7/numpy/random/mtrand
      compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/mike/Documents/repos/tools/cloudmapper/venv/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -c'
      gcc-8: numpy/random/mtrand/mtrand.c
      numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastCall':
      numpy/random/mtrand/mtrand.c:44374:13: error: too many arguments to function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth'
           return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':
      numpy/random/mtrand/mtrand.c:44793:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:44794:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:44795:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':
      numpy/random/mtrand/mtrand.c:44802:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44803:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44804:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44805:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44806:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44807:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':
      numpy/random/mtrand/mtrand.c:44862:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44863:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44864:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44865:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44866:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44867:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function '__Pyx_PyCFunction_FastCall':
      numpy/random/mtrand/mtrand.c:44374:13: error: too many arguments to function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth'
           return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionSave':
      numpy/random/mtrand/mtrand.c:44793:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:44794:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:44795:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function '__Pyx__ExceptionReset':
      numpy/random/mtrand/mtrand.c:44802:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44803:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44804:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44805:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44806:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44807:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function '__Pyx__GetException':
      numpy/random/mtrand/mtrand.c:44862:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44863:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44864:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44865:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44866:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44867:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      error: Command "/usr/local/bin/gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/mike/Documents/repos/tools/cloudmapper/venv/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/private -Ibuild/src.macosx-10.13-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o build/temp.macosx-10.13-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.macosx-10.13-x86_64-3.7/numpy/random/mtrand/mtrand.o.d" failed with exit status 1

      ----------------------------------------
  Command "/Users/mike/Documents/repos/tools/cloudmapper/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1v/2g9ck6_n21jcj6v8qtxc2h740000gn/T/pip-install-jiipx7dk/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/1v/2g9ck6_n21jcj6v8qtxc2h740000gn/T/pip-record-v8fah4bc/install-record.txt --single-version-externally-managed --prefix /private/var/folders/1v/2g9ck6_n21jcj6v8qtxc2h740000gn/T/pip-build-env-4aoynhyd --compile --install-headers /Users/mike/Documents/repos/tools/cloudmapper/venv/include/site/python3.7/numpy" failed with error code 1 in /private/var/folders/1v/2g9ck6_n21jcj6v8qtxc2h740000gn/T/pip-install-jiipx7dk/numpy/

  ----------------------------------------
Command "/Users/mike/Documents/repos/tools/cloudmapper/venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /private/var/folders/1v/2g9ck6_n21jcj6v8qtxc2h740000gn/T/pip-build-env-4aoynhyd --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None

**Comment by gmaentz** [comment]
downgrading to python 3.6.5 does work.  I have created a packer template to deploy on AWS for those interested.....http://www.maentz.net/pensieve/aznx5pjz92mc7jh6k86e5jxc9576k5

**Comment by 0xdabbad00** [comment]
This should be resolved now by using Pipenv and Python 3.7 as of #187
