### ISSUE TITLE
Need method for auditing domains

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#185]
Given route53 data for an account, need to be able to check the sub-domains to see if they point to things like non-existant buckets, which allow for easy sub-domain takeover.   The page response looks like:
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
....
```

I don't think CloudMapper should be responsible for looking for these things, as I don't know if the AWS data gives any insight that is helpful for this problem, but I should advise on what to do and maybe make a simple command to just extract out all of the subdomains for an account.

**Comment by FernandoMiguel** [comment]
Keep in mind a user can create multiple DNS zones with DNS records that are not actually glued to a domain

**Comment by 0xdabbad00** [comment]
I'm closing this as out of scope for CloudMapper at this time.
