### ISSUE TITLE
What if there are no CIDRs to input?

### ISSUE THREAD

**Issue by jeshan** [duo-labs/cloudmapper#190]
I'm getting output as these:
```
Building data for account jeshan (123456789012)
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
- 0 nodes built in region eu-west-1
- 0 nodes built in region ap-northeast-2
- 0 nodes built in region ap-northeast-1
- 0 nodes built in region sa-east-1
- 0 nodes built in region ca-central-1
- 0 nodes built in region ap-southeast-1
- 0 nodes built in region ap-southeast-2
- 0 nodes built in region eu-central-1
- 0 nodes built in region us-east-1
- 0 nodes built in region us-east-2
- 0 nodes built in region us-west-1
- 0 nodes built in region us-west-2
- 0 external CIDRs built
- 0 connections built
```
I saw you write in issue #165 that this "...likely means that CloudMapper did not identify any nodes in the network"

I don't understand why a CIDR is needed to visualise AWS architectures.

**Comment by 0xdabbad00** [comment]
You don't need to have any CIDRs.  But you do need at least an EC2, ELB, or RDS for the graph to display anything.  It looks like there are no resources in your account that CloudMapper knows how to display.

**Comment by jeshan** [comment]
OK what do you suggest if we don't have these? I'm thinking about Cloudformation designer which can support many more resources and without needing a CIDR

**Comment by 0xdabbad00** [comment]
It sounds like CloudMapper is not appropriate for your needs.  The network visualization only supports EC2s, ELBs, and RDS.
