### ISSUE TITLE
Collect data from Python

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#2]
Instead of running `collect_data.sh`, have the ability to collect this data via an argument like `python cloudmapper.py gather`

**Comment by gdahlm** [comment]
As awscli is just an abstraction of boto3 this is fairly trivial.

Note that the boto3 factory methods will also help with automating the JMESPaths needs, and may allow for broader service coverage without code changes.

Amazon maintains these datasources in the boto3 project to enable the factory methods for boto3 and it would be fairly easy to leverage their tools for your needs.

https://github.com/boto/boto3/tree/develop/boto3/data

This project is similar to one that I am working on leveraging networkx, and if python3 support is added I can possibly work on this need.  This will also work better with 2FA and other auth needs which may be hard for you to support using the aws-cli directly.

I opened an this issue to track the need for python3 support.

https://github.com/duo-labs/cloudmapper/issues/14
