### ISSUE TITLE
FR: Docker Image

### ISSUE THREAD

**Issue by vfarcic** [duo-labs/cloudmapper#20]
It might be useful to create a Docker image for the project.

**Comment by 0xdabbad00** [comment]
I don't have much experience with Docker. Would this be more useful as a Docker image vs a python package (https://github.com/duo-labs/cloudmapper/issues/1)?  My plan was to make it's setup just `pip install cloudmapper` and then running a few commands to configure an account, gather the AWS data, prepare it, and serving it as a webserver.  I think putting it in a Docker container might hide a lot of functionality.

**Comment by ngerstle** [comment]
Putting it in a docker container does obscure many of the options, but it makes it so much easier to deploy. Getting the aws-cli or the right python package dependency usually works, on most instances, but not always. It's why I've started to move towards go for similar tools.

Perhaps an additional alternative would be the use of a config file that allows toggling options, similar to the spf13/viper/cobra package combination? arguments override config, but a config file might more easily enable deployment as a running service.

That said, I only think it would be great to get it as a complete python package per #1

**Comment by cybergoof** [comment]
i recommend the python package even if docker.  Python package makes it easy to install.   Docker makes it easier to run.

**Comment by FernandoMiguel** [comment]
I've started building one 
https://github.com/FernandoMiguel/cloudmapper/blob/master/Dockerfile

I'll make a PR once it works

**Comment by FernandoMiguel** [comment]
PR submitted https://github.com/duo-labs/cloudmapper/pull/54

**Comment by ngerstle** [comment]
Resolved by #27
