### ISSUE TITLE
SQS get-queue-attributes does not return expected results

### ISSUE THREAD

**Issue by vingiarrusso** [duo-labs/cloudmapper#209]
When running the collection command, the files output after calling get_queue_attributes are incorrect.  The queue urls are valid, but the response from aws does not contain any attributes for the queue.

This is the response for a valid queue url, missing the attributes field we're looking for:
`{'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 29 Sep 2018 08:15:24 GMT', 'connection': 'keep-alive', 'content-length': '252', 'server': 'Server', 'content-type': 'text/xml', 'x-amzn-requestid': '-----'}, 'RequestId': '-----'}}`

According to the documentation for boto3 SQS client, get_queue_attributes can be called with AttributeNames, a list of potential attribute strings to filter for.  One solution that has worked for me is adding this as a parameter in `collect_commands.yaml`.  Doing so results in the response including the attributes field we're expecting.

**Comment by 0xdabbad00** [comment]
PR merged, so closing this. Thank you.
