### ISSUE TITLE
help with collect syntax

### ISSUE THREAD

**Issue by lrwilt** [duo-labs/cloudmapper#217]
I'm attempting to run collect with aws-vault and get-session-token for MFA, but I'm messing something up with the syntax, and I can't find an example that lists the full command. This is a generic form of what I am attempting:

aws-vault exec home -- aws sts get-session-token --serial-number arn:aws:iam::123456789101:mfa/user --token-code 111111 -- python cloudmapper.py collect --account my_account

**Comment by 0xdabbad00** [comment]
You'll want to run `aws-vault exec home --` first, and then run cloudmapper from within the environment it creates.  It looks like this is more an aws-vault usage issue than a CloudMapper issue.   You need to specify in your AWS profile (in `~/.aws/config`) that the profile uses an MFA.
