### ISSUE TITLE
Error is misleading

### ISSUE THREAD

**Issue by aubelsb2** [duo-labs/cloudmapper#222]
The error:
```            print("ERROR: AWS doesn't allow you to make IAM calls without MFA, and the collect command gathers IAM data.  Please use MFA.")```

At this location
https://github.com/duo-labs/cloudmapper/blob/65b9cf5a980269e841ce8dfcc051a628c915dc36/commands/collect.py#L113

Error should be that the client id is wrong:
https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html

**Comment by 0xdabbad00** [comment]
Good find. I'll make a change to identify what error AWS is actually responding with.  In my experience, not using MFA was a common cause for that error, so I'll point that out as a possible reason, but I shouldn't assume that's the only reason.

**Comment by timogoosenwork** [comment]
I was able to get cloudmapper working without MFA.

**Comment by nednones** [comment]
@timogoosenwork How did you manage to get Cloudmapper to work without MFA?

**Comment by timogoosenwork** [comment]
I just setup an IAM user with the seucityaudit policy attached to it.
I did a writeup of some of the instructions here:
https://yoirtuts.com/index.php?title=Setup_Cloudmapper

**Comment by 0xdabbad00** [comment]
Resolved in #251
