### ISSUE TITLE
Unable to access UI

### ISSUE THREAD

**Issue by AashishChughHome** [duo-labs/cloudmapper#224]
Hi

I just install cloud mapper and it is serving on local host but when i am accessing it with public-Ip:8000 , it is saying site is not reachable.

Should i need to do some extra configuration if i want to access it from another server.

Please suggest.

**Comment by 0xdabbad00** [comment]
You'll need to run `python cloudmapper.py webserver --public` otherwise it will not allow external hosts to access the webserver.
