### ISSUE TITLE
How to limit regions for the collect

### ISSUE THREAD

**Issue by davxiao** [duo-labs/cloudmapper#249]
I just wanted to scan `us-east-1` instead of full blown scan, where to set the limits? thanks

**Comment by 0xdabbad00** [comment]
There is not a way to limit the collection at this time.  You would have to make a small code-change here: https://github.com/duo-labs/cloudmapper/blob/9683957c1bb75b18639d9e0696ae41f1329f16f0/commands/collect.py#L146
