### ISSUE TITLE
collect_data.sh does not currently work when aws cli output is set to "table"

### ISSUE THREAD

**Issue by suryaprasad7500** [duo-labs/cloudmapper#25]
aws cli output for the profile being used has to be set to json

Maybe an addition to the instructions

**Comment by 0xdabbad00** [comment]
This should be resolved now due to https://github.com/duo-labs/cloudmapper/pull/26

**Comment by 0xdabbad00** [comment]
This adds `--output json` to each AWS CLI request so you can just `git pull` and try rerunning the script as previously.

**Comment by suryaprasad7500** [comment]
Yup. Just tested it out. It works!
Thank you
