### ISSUE TITLE
Edge missed between two EC2 instances

### ISSUE THREAD

**Issue by Atticuss** [duo-labs/cloudmapper#288]
### Issue and Steps to Reproduce

The final graph does not properly draw an edge between two EC2 nodes that are capable of communicating. Specifically, the EC2 are deployed to different VPCs in the same region and account. There is a peering connection between both VPCs and the route tables for both are configured to allow bidirectional communication. No NACLs exist. Each EC2 has their own security group. The SGs allow all traffic via SG ID (as opposed to a subnet CIDR or EC2 IP).

### Versions

CloudMapper 2.3.0

### Screenshots

CloudMapper output
![](https://user-images.githubusercontent.com/26174236/51952400-5ff7f480-2406-11e9-8bb2-4d5853640fae.png)

SSHing into the `cloudmapper test 2` instance.
<img width="716" alt="ssh-1" src="https://user-images.githubusercontent.com/26174236/51951980-a3516380-2404-11e9-8ae0-c3c4da52b4f2.png">

From the `cloudmapper test 2` shell, SSHing into the `cloudmapper test` instance.
<img width="565" alt="ssh-2" src="https://user-images.githubusercontent.com/26174236/51951991-aea48f00-2404-11e9-8422-1f0b49e45411.png">

The domain names, security group, and VPC of the `cloudmapper test` instance.
<img width="917" alt="ec2-console-1" src="https://user-images.githubusercontent.com/26174236/51951994-b2381600-2404-11e9-8e5a-20da600b1684.png">

The domain names, security group, and VPC of the `cloudmapper test 2` instance.
<img width="915" alt="ec2-console-2" src="https://user-images.githubusercontent.com/26174236/51951996-b5330680-2404-11e9-82f0-d8b7cbf30d27.png">

The SG configuration for the first EC2
<img width="832" alt="sg-1" src="https://user-images.githubusercontent.com/26174236/51952267-d516fa00-2405-11e9-9c7d-5c6480f8118a.png">

The SG configuration for the second EC2
<img width="838" alt="sg-2" src="https://user-images.githubusercontent.com/26174236/51952271-d811ea80-2405-11e9-8456-5bc5a0034520.png">

The route table configuration for the first VPC
<img width="859" alt="rt-1" src="https://user-images.githubusercontent.com/26174236/51952275-db0cdb00-2405-11e9-8946-6e51737f3782.png">

The route table configuration for the second VPC
<img width="867" alt="rt-2" src="https://user-images.githubusercontent.com/26174236/51952281-de07cb80-2405-11e9-98ef-1d2abb269f21.png">

The peering connection between the two VPCs
<img width="856" alt="pxc" src="https://user-images.githubusercontent.com/26174236/51952285-e19b5280-2405-11e9-8f04-04574ea696d5.png">

#### Expected

An edge should be drawn between the two EC2s.

#### Actual

No edge is drawn.

### Additional Details

I admittedly haven't done anything to investigate the cause for this behavior. If I get some free time in the future, I'll come back and see if I can dig it up.

**Comment by 0xdabbad00** [comment]
So in this situation, the edge is not shown because the nodes each are open to `0.0.0.0/0` so in order to avoid showing edges from every single node to these nodes, I only show the edge to `0.0.0.0/0`.  This is explained in https://duo.com/blog/spotting-misconfigurations-with-cloudmapper , see the image with caption `Modified visualization to show a more accurate view of what it looks like when everything is public.`   Mostly I did this because otherwise the graphs all looked like messes although it does cause confusion.

**Comment by 0xdabbad00** [comment]
Closing as I believe my explanation resolves this.
