### ISSUE TITLE
Have command to configure initial account setup

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#3]
Instead of editing `config.json`, have a command like `python cloudmapper.py configure`.

**Comment by JulesDT** [comment]
I tried to do this in this PR: https://github.com/duo-labs/cloudmapper/pull/37 using a simple Python generated CLI and dumping the resulting JSON file. I think this PR solves the issue :)

**Comment by 0xdabbad00** [comment]
I'd like to have this be command-line based, so using something like:
```
python cloudmapper.py configure add-account --id 1234567890123 --name demo --default True
python cloudmapper.py configure remove-account --id 1234567890123
python cloudmapper.py configure add-cidr --cidr 1.2.3.4/32 --name "Paris Office"
```

I'm also giving some thought to how much configuration we should bother doing at all for the accounts, as I never actually use the account ID, and the name of the account is just used to specify the folder to store the .json data in and to label the account in the diagram.

**Comment by 0xdabbad00** [comment]
Great work by @JulesDT in adding this functionality!
