### ISSUE TITLE
Feature request: Data flow between SNS, SQS, S3, Lambda

### ISSUE THREAD

**Issue by andresriancho** [duo-labs/cloudmapper#306]
## User story
As a cloud security auditor I would like to have a tool that shows me how AWS services exchange information so that I can better understand attack vectors.

I would like to see a new command in cloudmapper that graphs:
 * Messages sent to SNS topic X are sent to SQS queue Y
 * Lambda function Z is triggered when SQS Y message is received
 * S3Put on bucket W triggers ...

## Requirements
If SNS topic X are sent to SQS queue Y and lambda function Z is called when a message arrives to SQS queue Y, then that should be graphed as three dots (X, Y, Z) with lines connecting X->Y , Y-Z.

## References
[Tweet](https://twitter.com/AndresRiancho/status/1099053968687329288)

**Comment by andresriancho** [comment]
I don't have much time now, but will try to remember this issue for the future and might contribute with a PR.

**Comment by 0xdabbad00** [comment]
I'm hesitant on mapping this as I've run into complexity problems with the network mapping capability of CloudMapper (by which I mean the visual maps are too complex too understand). As a start, it would be good to just identify and list off what these integrations are.  That would help us understand just how many integrations might exist and possibly what filtering should be done on these.

**Comment by andresriancho** [comment]
At least for now, these are the ones that come to mind:
 * SNS
 * SQS
 * API Gateway
 * S3
 * Cloudformation (can send messages to SNS topic with events on how a stack is applied)
 * Lambda

**Comment by andresriancho** [comment]
I don't imagine this generating very complex graphs. I imagine one big graph (like the ones shown by `webserver` subcommand) with N graphs that have 2 or 3 edges and 1 or 2 lines.

Each edge would be one of SNS, SQS, API gateway, etc. The lines are drawn when there is a config in the edge service that will somehow invoke / call / message the next edge.

N will be large only if the AWS account has many integrations. Most accounts, at least in my experience, will have ~20 of these. If they do heavy use of this patterns, then it might be near 100.

**Comment by andresriancho** [comment]
![20190225_082438](https://user-images.githubusercontent.com/865200/53334252-fcfb5f80-38d6-11e9-9a7f-9e41d33feb5b.jpg)

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
