### ISSUE TITLE
Cannot Array Index with string "IPPermissions" Error.

### ISSUE THREAD

**Issue by rams3sh** [duo-labs/cloudmapper#307]
I was facing an error with running the public module of cloudmapper. The error log given below :-
````
Traceback (most recent call last):
  File "cloudmapper.py", line 70, in <module>
    main()
  File "cloudmapper.py", line 65, in main
    commands[command].run(arguments)
  File "/home/usercloudmapper/commands/public.py", line 22, in run
    public(accounts, config)
  File "/home/user/cloudmapper/commands/public.py", line 13, in public
    public_nodes, warnings = get_public_nodes(account, config)
  File "/home/user/cloudmapper/shared/public.py", line 123, in get_public_nodes
    sg_group_allowing_all_protocols = pyjq.first('select(.IpPermissions[]|.IpProtocol=="-1")|.GroupId', ingress, None)
  File "/usr/local/lib/python3.6/dist-packages/pyjq.py", line 66, in first
    return compile(script, vars, library_paths).first(_get_value(value, url, opener), default)
  File "_pyjq.pyx", line 223, in _pyjq.Script.first (_pyjq.c:2750)
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot index array with string "IpPermissions"
````

Much After debugging , found that pyjq was not able to get the nested dict as value for the key 'IPpermissions' due to some reason. Rewrote a dirty code to make it work. I dont know if anyone else is facing this problem or was it just me . 

The dirty code to replace the line 123 in shared/public.py below :-

````
sg_group_allowing_all_protocols= set()
for i in range(len(ingress)):
     for j in ingress[i].keys():
          if j == "IpPermissions":
               for k in range(len(ingress[i][j])):
                   if ingress[i][j][k].get('IpProtocol') == "-1":
                       sg_group_allowing_all_protocols.add(ingress[i].get('GroupId'))
````

Now it works .  Thought of putting this up as a bug so that someone similar to my issue can use this up.

**Comment by 0xdabbad00** [comment]
Thanks for reporting this. I'm curious if you have more information about your setup that might identify what the problem was so I can duplicate. Could you print the contents of `ingress` or tell me if that value is empty or some other issue?

**Comment by rams3sh** [comment]
Changed code snippet below (line 122) :-
![image](https://user-images.githubusercontent.com/5143597/54257698-3645f780-4586-11e9-9c09-0cf3c874da2a.png)

Output below :-
![image](https://user-images.githubusercontent.com/5143597/54258813-cdf91500-4589-11e9-9dee-9dcc3efd8a01.png)

Other Information regarding kernel info , python3 version and packages installed

```
osboxes@osboxes:~/cloudmapper$ uname -a
Linux osboxes 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
osboxes@osboxes:~/cloudmapper$ python3 --version
Python 3.6.7
osboxes@osboxes:~/cloudmapper$ python3 -c "print help('modules')"
  File "<string>", line 1
    print help('modules')
             ^
SyntaxError: invalid syntax
osboxes@osboxes:~/cloudmapper$ python3 -c "print (help('modules'))"

Please wait a moment while I gather a list of all available modules...

/usr/lib/python3/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
AptUrl              ast                 itertools           roman
CommandNotFound     asynchat            janitor             rsa
Crypto              asyncio             jmespath            runpy
DistUpgrade         asyncore            json                s3transfer
HweSupportStatus    atexit              keyring             scanext
IPython             audioop             keyword             sched
LanguageSelector    awscli              kiwisolver          scipy
NvidiaDetector      base64              language_support_pkgs seaborn
PIL                 bdb                 launchpadlib        secrets
PyInstaller         binascii            lib2to3             secretstorage
Quirks              binhex              libfuturize         select
UbuntuDrivers       bisect              libpasteurize       selectors
UbuntuSystemService boto3               linecache           setuptools
UpdateManager       botocore            locale              shapefile
__future__          brlapi              logging             shared
_ast                bs4                 louis               shelve
_asyncio            builtins            lsb_release         shlex
_bisect             bz2                 lzma                shutil
_blake2             cProfile            macaroonbakery      signal
_bootlocale         cairo               macholib            simplegeneric
_bz2                calendar            macpath             simplejson
_cffi_backend       certifi             macurl2path         site
_codecs             cgi                 mailbox             sitecustomize
_codecs_cn          cgitb               mailcap             six
_codecs_hk          chardet             mako                smtpd
_codecs_iso2022     chunk               markupsafe          smtplib
_codecs_jp          clonevirtualenv     marshal             sndhdr
_codecs_kr          cloudmapper         math                socket
_codecs_tw          cmath               matplotlib          socketserver
_collections        cmd                 maxminddb           softwareproperties
_collections_abc    code                mimetypes           soupsieve
_compat_pickle      codecs              mmap                speechd
_compression        codeop              modulefinder        speechd_config
_crypt              collections         multiprocessing     spwd
_csv                colorama            nacl                sqlite3
_ctypes             colorsys            netaddr             sre_compile
_ctypes_test        commands            netifaces           sre_constants
_curses             compileall          netrc               sre_parse
_curses_panel       concurrent          nis                 ssl
_datetime           configparser        nntplib             stat
_dbm                contextlib          ntpath              statistics
_dbus_bindings      copy                nturl2path          string
_dbus_glib_bindings copyreg             numbers             stringprep
_decimal            crypt               numpy               struct
_dummy_thread       cryptography        oauth               subprocess
_elementtree        csv                 olefile             sunau
_functools          ctypes              opcode              symbol
_gdbm               cups                operator            symtable
_geoslib            cupsext             optparse            sys
_hashlib            cupshelpers         orca                sysconfig
_heapq              curses              ordlookup           syslog
_imp                cycler              os                  systemd
_io                 datetime            ossaudiodev         tabnanny
_json               dateutil            pandas              tarfile
_locale             dbm                 parser              telnetlib
_lsprof             dbus                past                tempfile
_lzma               deb822              pathlib             termios
_markupbase         debconf             pcardext            test
_md5                debian              pdb                 tests
_multibytecodec     debian_bundle       pefile              textwrap
_multiprocessing    decimal             peutils             this
_opcode             decorator           pexpect             threading
_operator           defer               pickle              time
_osx_support        difflib             pickleshare         timeit
_pickle             dis                 pickletools         tkinter
_posixsubprocess    distro_info         pip                 token
_pydecimal          distro_info_test    pipenv              tokenize
_pyio               distutils           pipes               trace
_pyjq               doctest             pkg_resources       traceback
_random             docutils            pkgutil             tracemalloc
_sha1               dummy_threading     platform            traitlets
_sha256             easy_install        plistlib            tty
_sha3               email               policyuniverse      turtle
_sha512             encodings           poplib              types
_signal             enum                posix               typing
_sitebuiltins       errno               posixpath           ufw
_socket             faulthandler        pprint              unicodedata
_sqlite3            fcntl               problem_report      unittest
_sre                filecmp             profile             uno
_ssl                fileinput           prompt_toolkit      unohelper
_stat               fnmatch             pstats              urllib
_string             formatter           pty                 urllib3
_strptime           fractions           ptyprocess          usbcreator
_struct             ftplib              pwd                 uu
_symtable           functools           py_compile          uuid
_sysconfigdata_m_linux_x86_64-linux-gnu future              pyasn1              venv
_testbuffer         gc                  pyatspi             virtualenv
_testcapi           genericpath         pyclbr              virtualenv_support
_testimportmultiple geoip2              pydoc               wadllib
_testmultiphase     getopt              pydoc_data          warnings
_thread             getpass             pyexpat             wave
_threading_local    gettext             pygments            wcwidth
_tkinter            gi                  pygtkcompat         weakref
_tracemalloc        glob                pyjq                webbrowser
_warnings           grp                 pylab               wheel
_weakref            gzip                pymacaroons         wsgiref
_weakrefset         hashlib             pyparsing           xdg
_yaml               heapq               pypdb               xdrlib
abc                 hmac                pyproj              xkit
aifc                hpmudext            pyrfc3339           xml
altgraph            html                pytz                xmlrpc
antigravity         http                queue               xmltodict
apport              httplib2            quopri              xxlimited
apport_python_hook  idna                random              xxsubtype
apt                 imaplib             re                  yaml
apt_inst            imghdr              readline            zipapp
apt_pkg             imp                 reportlab           zipfile
aptdaemon           importlib           reprlib             zipimport
aptsources          inspect             requests            zlib
argparse            io                  requests_unixsocket zope
array               ipaddress           resource            
asn1crypto          ipython_genutils    rlcompleter         

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

None
```
Let me know if you need any other information

**Comment by james-martin-engineer** [comment]
ram3sh, did you manage to work around this? I am facing the exact same problem for a client on just one of their accounts. The code was cloned Friday and the server was built the same day from a current AWS Linux image.

Also, the exponential backoff-retry code is too aggressive forcing timeouts against the AWS API. 

The issue triggers for me only when generating a report.

**Comment by james-martin-engineer** [comment]
I was able to run a report by substituting an essentially 'default' document from a different region, then I encountered this on a 7th account after trying the same trick:
`
Traceback (most recent call last):
  File "cloudmapper.py", line 70, in <module>
    main()
  File "cloudmapper.py", line 65, in main
    commands[command].run(arguments)
  File "/home/master/cloudmapper/commands/report.py", line 292, in run
    dashboard(accounts, config, args)
  File "/home/master/cloudmapper/commands/report.py", line 214, in dashboard
    public_nodes, _ = get_public_nodes(account, config, use_cache=True)
  File "/home/master/cloudmapper/shared/public.py", line 123, in get_public_nodes
    sg_group_allowing_all_protocols = pyjq.first('select(.IpPermissions[]|.IpProtocol=="-1")|.GroupId', ingress, None)
  File "/usr/local/lib64/python3.7/site-packages/pyjq.py", line 66, in first
    return compile(script, vars, library_paths).first(_get_value(value, url, opener), default)
  File "_pyjq.pyx", line 223, in _pyjq.Script.first (_pyjq.c:2750)
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot index array with string "IpPermissions"
[root@AWS-CloudMap-PRD cloudmapper]#
`

This may be an upstream issue with the py/jq implementation,, or the jq binary we have is rubbish. :)

**Comment by 0xdabbad00** [comment]
It appears that the key `IpPermissions` is missing.  I'm curious what this Security Group is.  You could find this by running:
```
cat account-data/*/*/ec2-describe-security-groups.json | jq '.SecurityGroups[]|select(contains({IpPermissions})|not)'
```

**Comment by rams3sh** [comment]
@0xdabbad00  If you would have seen in the output I uploaded earlier, the key IpPermissions does exist but jq does not identify it. Have attached the output of the previous command below for reference :-

![image](https://user-images.githubusercontent.com/5143597/54542657-3e58c980-49c2-11e9-858e-3a28b347bb45.png)

Seems like it is a problem with jq. 

@james-martin-engineer : Hey check out my dirty work around in the initial issue request, you could use that for getting the output as of now.  That worked for me, should work for you as well.

**Comment by 0xdabbad00** [comment]
I had looked at the screenshot and it all looked fine to me, so I wondered if the problematic Security Group was elsewhere, but this confirms my assumption about the issue was not correct.

The relevant line of code is https://github.com/duo-labs/cloudmapper/blob/8e72f78747423aaa141a3cbfd46be8f8b9f3bf10/shared/public.py#L123

The check is just to print a warning if it finds a match for something, which is going to be moved into the auditing code soon as opposed to this location, so this code will be removed from this location eventually, but it'll be the same code when I move it, so I don't like that this is causing problems.

I suspect it is not an issue with jq, but rather me making an assumption about the format of the data which ends up being wrong for your cases.

**Comment by rams3sh** [comment]
I checked the code manually , but however I find your format being logically right even though it is giving errors. Also , logically  the format of ec2-describe-instances will be standard.

Anyways , last check .. I dont know if it is problem with the jq version or something . Can you let me know if your version of jq is similar to this .

![image](https://user-images.githubusercontent.com/5143597/54543620-fa66c400-49c3-11e9-84e5-c9df17f403cb.png)

Also @james-martin-engineer  : can you check on your version as well.

**Comment by 0xdabbad00** [comment]
I'm at:
```
$ jq --version
jq-1.5
$ pip3 freeze | grep jq
pyjq==2.1.0
```

It shouldn't make a difference, but it is interesting that you're on pyjq==2.3.1, as the Pipfile specifies 2.1.0. https://github.com/duo-labs/cloudmapper/blob/8e72f78747423aaa141a3cbfd46be8f8b9f3bf10/Pipfile#L7

You would need to enter the pipenv (`pipenv shell`) to ensure you're in the environment with the specific pyjq library.

**Comment by rams3sh** [comment]
Hmm .. Actually I didnt setup a separate virtual environment.  

I am using cloudmapper in my native environment.

**Comment by 0xdabbad00** [comment]
Make sure you run the instructions to run:
```
pipenv install --skip-lock
pipenv shell
```

**Comment by james-martin-engineer** [comment]
I am using the virtual environment, my pyjq version is as follows:
```
Name: pyjq
Version: 2.1.0

```
jq also shows version 1.5. At least for me, the version of pyjq does not seem to change the outcome of these IPPermissions bug.

I've also run your
cat account-data/*/*/ec2-describe-security-groups.json | jq `'.SecurityGroups[]|select(contains({IpPermissions})|not)'`

command over the data set. It doesn't return anything, and from a grep over IpPermissions for the problem data sets, all IpPermissions blocks appear to be populated with legal values.

**Comment by james-martin-engineer** [comment]
Hi All,

Ram3sh, I've updated your patch to include another link to freeze the sets that your patch creates, otherwise the following line throws an exception that set is not immutable
`            public_sgs.add(sg_group_allowing_all_protocols)`

error:
`TypeError: unhashable type: 'set'`

Ram3sh's fixed code patch to replace line 123:
```
        for i in range(len(ingress)):
             for j in ingress[i].keys():
                  if j == "IpPermissions":
                       for k in range(len(ingress[i][j])):
                           if ingress[i][j][k].get('IpProtocol') == "-1":
                               sg_group_allowing_all_protocols.add(ingress[i].get('GroupId'))
        #make sg_group_allowing_all_protocols immutable
        sg_group_allowing_all_protocols = frozenset(sg_group_allowing_all_protocols)
```

**Comment by rams3sh** [comment]
Was checking the data by dumping the ingress to json and found that the error was in the jq query. 
The json in ingress starts with square bracket. Hence the query was giving issues. 

Changing the line 123 of  cloudmapper/shared/public.py
from

`sg_group_allowing_all_protocols = pyjq.first('select(.IpPermissions[]|.IpProtocol=="-1")|.GroupId', ingress, None)`

to

`sg_group_allowing_all_protocols = pyjq.first('.[] | select(.IpPermissions[]|.IpProtocol=="-1")| .GroupId', ingress, None)`

solved this issue.

**Comment by 0xdabbad00** [comment]
This should hopefully be resolved now as of #462

**Comment by rams3sh** [comment]
I dont think current commit would resolve the issue. I have added my suggestion in the committed code. Can you please check it ?

**Comment by 0xdabbad00** [comment]
@rams3sh Can you provide a test case case?  Just a minimal sample of data from `ec2-describe-security-groups.json` from you data that breaks the following:
```
cat account-data/demo/us-east-1/ec2-describe-security-groups.json | jq '.SecurityGroups[] | .IpPermissions[]?.IpRanges[]|[.CidrIp,.Description]'
```

**Comment by rams3sh** [comment]
I had deleted the last set of files that gave me this issue and I no longer have that.

However, I ran the above command and it doesnt break for any of the collected json files.

Have deleted my comment from your code.
