### ISSUE TITLE
Display large environments

### ISSUE THREAD

**Issue by jacobelzey** [duo-labs/cloudmapper#31]
What would be the recommended config or steps to display a very large environment?

I am not able to display what we have currently, using the built-in web server mentioned or another web server like IIS. Willing to use something else, just not sure what was suggested.

**Comment by 0xdabbad00** [comment]
Your best option will be to filter down how many nodes and edges you are trying to display by adding some filtering options in the `prepare` command.  I'm going to document these better shortly, but you can see them when you run `--help` or look here: https://github.com/duo-labs/cloudmapper/blob/c1b3dff043a25d46190cd5b7178f64215db455b3/cloudmapper.py#L52

Your browser or web server should not make a difference.

**Comment by jacobelzey** [comment]
Awesome, thank you

**Comment by 0xdabbad00** [comment]
Documented in the README in https://github.com/duo-labs/cloudmapper/commit/2a0a5d1230505f8a04f5d284d76d6ba6ad7398b8#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by jacobelzey** [comment]
Thanks! I was able to break it down and start on a simpler showing. Is there an option to filter by VPC?
