### ISSUE TITLE
Where does cloudmapper search for credentials?

### ISSUE THREAD

**Issue by Duke126876** [duo-labs/cloudmapper#315]
I have satisfied pre-requisites and have it installed, however, when I run the following, I get an error:

python cloudmapper.py collect --account Non-Prod
ERROR: sts.get_caller_identity failed with InvalidClientTokenId. Likely cause is no AWS credentials are set.

Where does cloudmapper look for AWS credentials? I have requested a temporary token using MFA and have the credentials pasted in /root/.aws/credentials, but it seems as if cloudmapper is not checking that file for credentials. I have also exported the secret key, access key, and session token to my env. Please advise.

**Comment by FernandoMiguel** [comment]
Take a look at aws-vault project.
It will keep your credentials secure and support multiple roles and MFA. 

You can execute it in server mode and your Docker will just consume the credentials from your host.

**Comment by 0xdabbad00** [comment]
At the command-line, you should be able to run the AWS CLI command `aws sts get-caller-identity` (exactly like that).  If that doesn't work, your credentials are not configured for your environment.  A common workflow for me looks like:
```
aws-vault exec prod --no-session --
python cloudmapper.py collect --account prod
```

**Comment by Duke126876** [comment]
See below. If I use my Non-Prod profile, I get a response from the API call. Numbers have been changed for security. Also, I am executing cloudmapper in a virtualenv. Not sure if that is causing issues. 

[root@prd-utl-01 cloudmapper]# aws sts get-caller-identity --profile dev_uat
------------------------------------------------------------------------------------------------
|                                       GetCallerIdentity                                      |
+--------------+-----------------------------------------------------+-------------------------+
|    Account   |                         Arn                         |         UserId          |
+--------------+-----------------------------------------------------+-------------------------+
|  123456|  arn:aws-us-gov:iam::123456:user/tyleryosick  |  123456|
+--------------+-----------------------------------------------------+-------------------------+

**Comment by Duke126876** [comment]
When I try to execute cloudmapper using that same profile, I still receive the error. 

(cloudmapper) [root@prd-utl-01 cloudmapper]# python cloudmapper.py collect --account Non-Prod --profile dev_uat
ERROR: sts.get_caller_identity failed with InvalidClientTokenId. Likely cause is no AWS credentials are set.

**Comment by 0xdabbad00** [comment]
There could be issues due to you having what looks like a gov cloud account.  I know others have gotten CloudMapper to work with govcloud, but I don't have experience with it, and that environment isn't as well tested.

I strongly recommend you use aws-vault, as that use case is both better tested, and aws-vault has other security benefits.  https://github.com/99designs/aws-vault

**Comment by dginther** [comment]
Having the same problem here. Credentials are configured just fine for everything I need to do on a regular basis, but your tool doesn't see the credentials in either a ~/.aws/credentials file, or in the environment at AWS_ variables. Telling someone to use another credential management system is all well and good but this is a bug in your application, not a problem that requires aws-vault.

The initial question still stands, _Where does cloudmapper search for credentials_? It's not ~/.aws/credentials and it's not in the environment. Where is it?

**Comment by dginther** [comment]
@Duke126876 , I figured it out. The AWS_REGION is pulled from your environment, not from your config file, and it is defaulted to us-east-1 here. You have to set it in your environment if you want differently.

**Comment by 0xdabbad00** [comment]
CloudMapper uses botocore which will search for creds in a number of places (including ~/.aws/credentials and the environment variables).  See https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html

For specifically when in the code CloudMapper gets creds, it is https://github.com/duo-labs/cloudmapper/blob/master/commands/collect.py#L165

As you can see it is simply calling boto and letting boto handle the cred collection.  For this reason, I strongly believe this is not a bug in CloudMapper, but appears to be an issue with how people are using CloudMapper.

**Comment by dginther** [comment]
It's technically a bug in your application as you are defaulting to us-east-1 as the region, and not pulling that from the credentials file, but from ENV variables, and you don't mention that you would need to set your AWS_REGION env variable in your documentation.

**Comment by 0xdabbad00** [comment]
Defaulting to us-east-1 should "just work" for the AWS commercial region.  I don't have access to a gov-cloud account though or any other AWS partitions.  If the code needs to be changed it is at https://github.com/duo-labs/cloudmapper/blob/master/commands/collect.py#L158

If you'd like to see this fixed @dginther, I would need more info as I can't replicate your problem, or you're welcome to send a PR.

**Comment by dginther** [comment]
🤷‍♂ Turns out I can't use it in govcloud anyway because there are no STS endpoints supported in govcloud, so...

But maybe just document that if you want to default to another region, you need to set an ENV var?

**Comment by rirze** [comment]
Commenting to say this bit me when using this tool. As soon as I set the environment var, it started collecting. 

I took a look at how the code obtains session parameters-- I would recommend an approach similar to https://github.com/FSecureLABS/awspx/blob/1be60eed68263068f5856427e5a495518d27290a/cli.py#L66
 that obtains the same credentials from the boto3 directly.
