### ISSUE TITLE
Account named _______ not found.

### ISSUE THREAD

**Issue by damianesteban** [duo-labs/cloudmapper#34]
This tool works perfectly up until the "prepare" phase, when I get the following error:

```
$ python cloudmapper.py prepare --account production
Traceback (most recent call last):
  File "cloudmapper.py", line 146, in <module>
    main()
  File "cloudmapper.py", line 134, in main
    run_prepare(arguments)
  File "cloudmapper.py", line 109, in run_prepare
    account = get_account(args.account_name, config)
  File "cloudmapper.py", line 41, in get_account
    raise Exception("Account named \"{}\" not found".format(account_name))
Exception: Account named "production" not found

```

I used the same account name in the previous step without issue.

**Comment by lukehankins** [comment]
I got a similar error.  Do you have a config.json set up with that account name in it?  (The error might be more helpful if it identified the name of the file it couldn't find the account name in.)

**Comment by 0xdabbad00** [comment]
Yeah, this looks like your `config.json` file must not have a `production` account configured in it.  I just added some error handling to look for this case: https://github.com/duo-labs/cloudmapper/commit/fc1b824542fd95854ba6b0000fd30bbdedc04a45

Please close the ticket @damianesteban if this resolves your problem.

**Comment by 0xdabbad00** [comment]
I believed this has been resolved, so I'm closing this.
