### ISSUE TITLE
Feature Request : Change in Format of reporting of "public_sgs" in public command for better stndardization

### ISSUE THREAD

**Issue by rams3sh** [duo-labs/cloudmapper#373]
I am using the output of "public" command to analyze my infra and to build on a personal automation script. 
While I was reviewing the json output of public command , I noted that the security groups that are reason for a specific component to be public , is given in following format :- 

```
"public_sgs": {
        "sg-randomgroupid": {
            "GroupName": "randomgroupname",
            "public_ports": "randomport"
        }
    }

```

Here the securitygroup's id itself becomes a subsequent key for further values. This results in non-standard keys across the output. It would be great if a standard format is followed something like the following :-

```
"public_sgs":
        [
	   { "sg_id" : "sg-randomgroupid","GroupName": "randomgroupname","public_ports": "randomport"},
	   {.........}
	]
```

This would help in maintaining standard set of key.

**Comment by 0xdabbad00** [comment]
It sounds like you're interested in the output being an array as opposed to a dictionary here.

**Comment by rams3sh** [comment]
Well .. I dont mind it being dictionary either . I was focusing more on having a key whose value could be the  security group Id . Currently the security group Id is not represented as a value in the output , it is represented as a key.  Since this security group ID is unique , there would not be  a standard key which can be used to query this id . Hence this request. 

I understand that there  are ways by which I can get the security group Id through simple jq query, but thought a standardized structure will be great.  It might be just my thinking , but never the less , I thought of raising it as an issue , if anyone sees any value in this issue request. !!

**Comment by 0xdabbad00** [comment]
I'm not sure what you mean.  Currently the Security Group ID is printed out.  The code for this is: https://github.com/duo-labs/cloudmapper/blob/f6da8a4a368653ec8ecd36f24d013b3d127aa5bb/shared/public.py#L141

The `GroupId` is the Security Group ID.

**Comment by rams3sh** [comment]
I made a small snippet output of the public command into a file  and have given a small demo using jq on what I was intending to achieve . Image below :- 
![image](https://user-images.githubusercontent.com/5143597/57029478-790b7e00-6c5f-11e9-87b1-0365f8baa999.png)

Hope I am able to convey my ask !

**Comment by w0rmr1d3r** [comment]
Hello @rams3sh and @0xdabbad00 
I believe it can conserve the dictionary and add the id with this PR
https://github.com/duo-labs/cloudmapper/pull/857
