### ISSUE TITLE
pyjq install osx high sierra

### ISSUE THREAD

**Issue by snomann** [duo-labs/cloudmapper#38]
[error.log](https://github.com/duo-labs/cloudmapper/files/1748850/error.log)

**Comment by 0xdabbad00** [comment]
See if you have `autoreconf` installed.  `which autoreconf` should return `/usr/local/bin/autoreconf`.
If not, run `brew install autoconf`

**Comment by snomann** [comment]
It was resolving to /opt/chefdk/embedded/bin/autoreconf due to chefdk configuration. That was causing some issues. Disabling chefdk solved this.
