### ISSUE TITLE
404 on data.json

### ISSUE THREAD

**Issue by mrichman** [duo-labs/cloudmapper#404]
I've run `./cloudmapper.py collect` which has generated lots of data for my environment. I see that data in the `account-data` directory.

Running `./cloudmapper.py stats` shows me information as expected.

However, when I run `./cloudmapper.py webserver` and browse, I never see anything populate. When I look in the browser console, I see a 404 on http://localhost:8000/data.json.

**Comment by 0xdabbad00** [comment]
You need to run `python cloudmapper.py prepare --account ...` in order to generate `data.json`

Related to #39, I never got around to showing an error for this.

**Comment by mrichman** [comment]
Worked, thanks.
