### ISSUE TITLE
botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by bmcdonough** [duo-labs/cloudmapper#41]
Must have ~/.aws/credentials file containing:
`[default]`
`aws_access_key_id=XXXXXXXXXXXXXX`
`aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYY`

**Comment by 0xdabbad00** [comment]
It sounds like you resolved your issue?  I'm closing this as configuring your account with boto or the aws cli is outside the scope of this project.
