### ISSUE TITLE
pyjq.ScriptRuntimeError: Cannot iterate over null (null) - Prepare module

### ISSUE THREAD

**Issue by j-maciak** [duo-labs/cloudmapper#412]
I already tried the fixes mentioned in [#205](https://github.com/duo-labs/cloudmapper/issues/205) to no avail. The error is as follows:

> [test@srv cloudmapper]# python3.7 cloudmapper.py prepare --account diagram
> Building data for account diagram (019305184864)
> Traceback (most recent call last):
>   File "cloudmapper.py", line 73, in <module>
>     main()
>   File "cloudmapper.py", line 67, in main
>     commands[command].run(arguments)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 649, in run
>     prepare(account, config, outputfilter)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 569, in prepare
>     cytoscape_json = build_data_structure(account, config, outputfilter)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 306, in build_data_structure
>     for region_json in get_regions(account, outputfilter):
>   File "/home/scripts/3rdparty/cloudmapper/shared/common.py", line 126, in get_regions
>     regions = pyjq.all('.Regions[]{}'.format(region_filter), region_data)
>   File "/usr/local/lib/python3.7/site-packages/pyjq.py", line 49, in all
>     return compile(script, vars, library_paths).all(_get_value(value, url, opener))
>   File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
> _pyjq.ScriptRuntimeError: Cannot iterate over null (null)

**Comment by chrisswanda** [comment]
I fixed mine by adding the "?" to:

`return pyjq.all('.SecurityGroups[]?.GroupId', self._json_blob)`
autoscaling_name = pyjq.all('.Tags[]? | select(.Key == "aws:autoscaling:groupName") | .Value', json_blob)

collapse_by_tag_value = pyjq.all('.Tags[]? | select(.Key == "{}") | .Value'.format(collapse_by_tag), json_blob)

**Comment by j-maciak** [comment]
Still the same error after making those edits to nodes.py:

> [test@srv cloudmapper]# python3.7 cloudmapper.py prepare --account diagram
> Building data for account diagram (019305184864)
> Traceback (most recent call last):
>   File "cloudmapper.py", line 73, in <module>
>     main()
>   File "cloudmapper.py", line 67, in main
>     commands[command].run(arguments)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 649, in n
>     prepare(account, config, outputfilter)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 569, in epare
>     cytoscape_json = build_data_structure(account, config, outputfilter)
>   File "/home/scripts/3rdparty/cloudmapper/commands/prepare.py", line 306, in ild_data_structure
>     for region_json in get_regions(account, outputfilter):
>   File "/home/scripts/3rdparty/cloudmapper/shared/common.py", line 126, in getegions
>     regions = pyjq.all('.Regions[]{}'.format(region_filter), region_data)
>   File "/usr/local/lib/python3.7/site-packages/pyjq.py", line 49, in all
>     return compile(script, vars, library_paths).all(_get_value(value, url, oper))
>   File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
> _pyjq.ScriptRuntimeError: Cannot iterate over null (null)

**Comment by j-maciak** [comment]
Can I get an answer on this? This seems to be a very common bug that is still unresolved.

**Comment by 0xdabbad00** [comment]
@j-maciak I don't have any enough information to be able to fix this.  I've run CloudMapper in a lot of accounts, but have not experienced some of the issues others are seeing and I'm unsure how to resolve them.  I maintain this open-source project, but I run my own consulting business (ie. I am not a Duo employee). I maintain and improve this project in my free time.  As a result I am not able to support this at a level you might expect from paid software. 

Thank you @chrisswanda for finding a fix to your problem and the one @j-maciak is experiencing.  Do you know why you didn't have those arrays though?  It implies to me that possibly the file was not downloaded correctly somehow during the collect phase?

**Comment by 0xdabbad00** [comment]
Appears related to #205

**Comment by 0xdabbad00** [comment]
Should be resolved by #432

**Comment by chrisswanda** [comment]
@0xdabbad00

> Do you know why you didn't have those arrays though?

I have no clue.  I've been running Cloudmapper on a couple of production accounts, just to get a visual snapshot on-demand, every now and then.  I'm not sure what version I was running, but did a git pull and afterwards is when I noticed this error.  So, I cannot point my finger at how, where or how.

**Comment by davidprowe** [comment]
./shared/common.py - still has an issue from this. I experienced the same thing and the same error:

File "/home/ec2-user/cloudmapper/shared/common.py", line 161, in get_regions
    regions = pyjq.all(".Regions[]{}".format(region_filter), region_data)
(mine was just a different line number)

Adding the "?" to line 161 allowed me to prepare the data without any errors
    regions = pyjq.all(".Regions[]?{}".format(region_filter), region_data)

**Comment by Sytten** [comment]
Same error, but the fix above does not work. It seems to happen if the region was empty, it will then say `Exception: us-east-1 not found`.

**Comment by davidprowe** [comment]
Try removing dashes, underscores, and capital letters from your account
name and matching the account alias in the config.json with the AWS profile
name

**Comment by Sytten** [comment]
Yeah the problem was that the account name was not matching the name of the folder the data was in for some weird reason :S
