### ISSUE TITLE
Provide filter for single VPC

### ISSUE THREAD

**Issue by mark-greene** [duo-labs/cloudmapper#42]
I always get the "Default" VPC along with the VPC of interest in a region.

**Comment by 0xdabbad00** [comment]
Not currently. I'll add the ability to filter on this soon.

**Comment by alanquillin** [comment]
To expound on this, it would be nice to be ab be able to not only filter by 1 VPC but pass in a list of VPC to include and/or possibly a list to exclude

**Comment by 0xdabbad00** [comment]
@alanquillin Added this functionality in #63   I'll review shortly.

**Comment by 0xdabbad00** [comment]
Resolved in #63
