### ISSUE TITLE
Support for internet gateways

### ISSUE THREAD

**Issue by mallory-at-hp** [duo-labs/cloudmapper#428]
I just created a visualization of an account I have access to - however, the graph does not show any internet gateway. Is that a defect, something you plan to add down the the road or am I missing something?

**Comment by 0xdabbad00** [comment]
CloudMapper's network visualization works based on Security Groups.  Internet Gateways don't have Security Groups.  Therefore, CloudMapper does not work with it.  It would also require adding functionality to understand route tables.

**Comment by 0xdabbad00** [comment]
Closing as out of scope for the current goals of CloudMapper.
