### ISSUE TITLE
Set AWS secrets via ENV variables

### ISSUE THREAD

**Issue by sahal** [duo-labs/cloudmapper#43]
It doesn't look like this is currently possible.

**Comment by 0xdabbad00** [comment]
The `collect_data.sh` script just wraps the aws cli which will use the AWS related environmental variables by default.  Likewise, using `cloudmapper.py gather` uses boto which does this by default, so I'm not sure what you mean.  Can you explain further?

**Comment by sahal** [comment]
I think this default behavior in boto3/awscli is reset with the following lines:

- https://github.com/duo-labs/cloudmapper/blob/master/cloudmapper.py#L44
- https://github.com/duo-labs/cloudmapper/blob/master/collect_data.sh#L45

```
(ins)(venv) [~/build/cloudmapper]$ aws-vault exec REDACTED -- python cloudmapper.py gather
Enter token for arn:aws:iam::REDACTED:mfa/REDACTED: REDACTED
usage: cloudmapper.py [-h] --account-name ACCOUNT_NAME
cloudmapper.py: error: argument --account-name is required
(ins)(venv) [~/build/cloudmapper]$ aws-vault exec REDACTED -- ./collect_data.sh
* Startup checks
ERROR: No account Name Specified
Usage:
  ./collect_data.sh --account my_account [--profile aws_profile]
```

**Comment by 0xdabbad00** [comment]
You just need to supply your account name, so you should be running:
```
aws-vault exec REDACTED -- python cloudmapper.py gather --account-name your_account
```

I could have cloudmapper provide a default name for your account, or identify your account ID if it has AWS access and use your account ID as your account name.  Those are possibilities.  I think it's better to ensure the user specifies which account they are interested in though, as many users have many accounts.
