### ISSUE TITLE
audit_s3_buckets has undefined variables

### ISSUE THREAD

**Issue by langelgjm** [duo-labs/cloudmapper#444]
https://github.com/duo-labs/cloudmapper/blob/master/shared/audit.py#L56

```                        else:
                            findings.add(Finding(
                                region,
                                'S3_PUBLIC_POLICY',
                                bucket,
                                resource_details=policy_string))
                            region, issue_id, resource_id, resource_details
```

None of the variables on the final line are defined in this function's scope, which leads to a Exception downstream. Looks like this line was just accidentally dropped here. Removing it causes the code to work.

**Comment by jdnrg** [comment]
this line actually does not do any thing and can be commented out.
