### ISSUE TITLE
Using CloudMapper without all the needed permissions

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#446]
Paul Wakeford asked "Has anyone tried using Duo CloudMapper in an account where EC2 access is denied using an Org SCP? I'm having no luck - immediate fail to enumerate regions."

**Comment by 0xdabbad00** [comment]
I'm of the opinion that this is currently outside of the scope of CloudMapper's goals.  I assume I have all the needed permissions (SecurityAudit and ViewOnlyAccess) when CloudMapper runs.  Although I could work around this specific issue, generically, this isn't a problem I want to solve and I don't think it is common enough.  For example, although in this case ec2 was denied, what happens if some other priv is denied?  I don't want to consider the logic of each of these types of failures and how to work around them.  This is the first time I had heard of this being done in an environment.

**Comment by paulwakeford** [comment]
'I assume I have all the needed permissions (SecurityAudit and ViewOnlyAccess) when CloudMapper runs. '

These don't help if an SCP denies access. 
Thinking out loud, there's an API to get enabled regions now, and that to get regions plus resuming on error (with logging) could work?
