### ISSUE TITLE
keyError: 'Critical' during report command

### ISSUE THREAD

**Issue by devinnasar** [duo-labs/cloudmapper#451]
Hello, When I run the following command:
```bash
(cloudmapper) dnasar@OTPHWKLT0063:~/src/cloudmapper$ python cloudmapper.py report --config config.json --account my-account
```

I receive this error:

```python
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 374, in run
    report(accounts, config, args)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 263, in report
    count = findings_severity_by_account[finding.account_name][conf['severity']].get(finding.issue_id, 0)
KeyError: 'Critical'
```
I'd appreciate any help you could provide. Thanks!

**Comment by 0xdabbad00** [comment]
Looks like I forgot to add a value for `Critical` at https://github.com/duo-labs/cloudmapper/blob/46bcb7218cf3196516909ae294cf7ecb2952d38f/commands/report.py#L21

I'll update soon with a line for:
```
 {'name': 'Critical', 'color': 'rgba(255, 0, 0, 1)'},  # Bright red
```

**Comment by devinnasar** [comment]
Hello,

I added that line to report.py, it throws something fairly deep:

```python
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 375, in run
    report(accounts, config, args)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 344, in report
    'details': json.dumps(finding.resource_details, indent=4)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type NameError is not JSON serializable
```

The problem seems to be happening because my account is reporting a Critical finding. A clue to what might be going on might be here:

When I run
`(cloudmapper) dnasar@OTPHWKLT0063:~/src/cloudmapper$ python cloudmapper.py audit --config config.json --account MyAccount`

the sole Critical Error looks to be the following:
```
HIGH - MyAccount (us-east-1) - Internet accessible S3 bucket via policy: mycompany-status
CRITICAL - MyAccount (us-east-1) - An exception occurred during the audit.: mycompany-status
```

When I look at audit_config.yaml, it seems that at least conventionally that cloudmapper is designed to fail if a Critical issue is found, however I'm getting almost not information as to what the issue is to correct it. Is this right?

**Comment by 0xdabbad00** [comment]
Ah, yes, I was using the `CRITICAL` error for exceptions.  

At this line, https://github.com/duo-labs/cloudmapper/blob/3b9a2e81e3f2741dd11b16bd7e809b6fbbf5ce8f/commands/report.py#L343

try adding:
```
print(finding.resource_details)
```

Hopefully that will help track this down further.

**Comment by devinnasar** [comment]
I placed your print statement as such:
```python
# ...
        region_hits['hits'].append({
            'resource': finding.resource_id,
            'details': json.dumps(finding.resource_details, indent=4)
        })
        print(finding.resource_details) # line 346
# ...
```


```

Command output as follows:

```
(cloudmapper) dnasar@OTPHWKLT0063:~/src/cloudmapper$ python cloudmapper.py report --config config.json --account MyAccount
* Getting resource counts
  - MyAccount
* Getting IAM data
  - MyAccount
* Getting public resource data
  - MyAccount
* Auditing accounts
WARNING:policyuniverse:ARN Could not parse [AIDAJMKMMLERSNARFBLAT].
WARNING:policyuniverse:Auditor could not parse ARN AIDAJMKMMLERSNARFBLAT.
WARNING:policyuniverse:ARN Could not parse [AIDAJMKMMLERSNARFBLAT].
WARNING:policyuniverse:Auditor could not parse ARN AIDAJMKMMLERSNARFBLAT.
WARNING:policyuniverse:ARN Could not parse [AIDAI66TZDINGLEHOPPER].
WARNING:policyuniverse:Auditor could not parse ARN AIDAI66TZDINGLEHOPPER.
WARNING:policyuniverse:ARN Could not parse [AIDAI66TZDINGLEHOPPER].
WARNING:policyuniverse:Auditor could not parse ARN AIDAI66TZDINGLEHOPPER.
WARNING:policyuniverse:ARN Could not parse [AIDAI66TZDINGLEHOPPER].
WARNING:policyuniverse:Auditor could not parse ARN AIDAI66TZDINGLEHOPPER.
WARNING:policyuniverse:ARN Could not parse [AIDAI66TZDINGLEHOPPER].
WARNING:policyuniverse:Auditor could not parse ARN AIDAI66TZDINGLEHOPPER.
None
None
None
{'Grantee': {'Type': 'Group', 'URI': 'http://acs.amazonaws.com/groups/global/AllUsers'}, 'Permission': 'READ'}
None
None
None
None
None
None
None
None
None
None
None
{"Version":"2012-10-17","Statement":[{"Sid":"AddPerm","Effect":"Allow","Principal":"*","Action":"s3:GetObject","Resource":"arn:aws:s3:::mycompany-status/*"},{"Sid":"Stmt1556737656635","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::01189998819991197253:user/jschmoe"},"Action":["s3:DeleteObject","s3:GetObject","s3:PutObject"],"Resource":"arn:aws:s3:::mycompany-status/*"},{"Sid":"Stmt1556737656636","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::01189998819991197253:user/jschmoe"},"Action":"s3:ListBucket","Resource":"arn:aws:s3:::mycompany-status"}]}
Traceback (most recent call last):
  File "cloudmapper.py", line 73, in <module>
    main()
  File "cloudmapper.py", line 67, in main
    commands[command].run(arguments)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 376, in run
    report(accounts, config, args)
  File "/home/dnasar/src/cloudmapper/commands/report.py", line 344, in report
    'details': json.dumps(finding.resource_details, indent=4)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type NameError is not JSON serializable
```

**Comment by schosterbarak** [comment]
👍

**Comment by 0xdabbad00** [comment]
The commit from #458 should better print the exception now. Unfortunately I still don't know what caused the original exception.

**Comment by schosterbarak** [comment]
@0xdabbad00 last master commit did the trick for me. From my experience this ticket can be marked as resolved.

**Comment by 0xdabbad00** [comment]
Thanks @schosterbarak
