### ISSUE TITLE
Provide a way to collapse named CIDR ranges

### ISSUE THREAD

**Issue by lukehankins** [duo-labs/cloudmapper#48]
If I have a /30 as a named range in my config.json, but a security group references just a /32 in that range, it would be nice to have an option to have the connection terminate at the /30 rather than having a separate node for the /32.

**Comment by 0xdabbad00** [comment]
Good idea.  I'll see what I can do with regard to matching up CIDR ranges.

**Comment by andywirv** [comment]
Adding to this as I was looking to be able to "collapse CIDR ranges" for Akamai Siteshield. My use case is slightly different though. I have a list of 24 CIDRs that should all with the same name. Currently that results in one item for each even though they have the same name

**Comment by livehybrid** [comment]
👍 On this, We have about 12 IP ranges as potential outbound IPs from our office, this currently creates 12 locations, and 12 lines each time these are referenced in a SG

**Comment by 0xdabbad00** [comment]
Resolved by #389
