### ISSUE TITLE
Reduce the size of data.json

### ISSUE THREAD

**Issue by yoava333** [duo-labs/cloudmapper#481]
Currently, every node_data contains the entire node data, in a connected graph this means that node_data is duplicated many times, in an environment with 300 nodes and 70k edges the resulting json file was ~2.5GB!
I removed node_data from the json the this reduced the file size to ~10MB.

I suggest splitting the data in `node_data` and reference (an index to a second array) in each node, trying this out reduced the size of the json to ~18MB and didn't change the information in the json.

**Comment by 0xdabbad00** [comment]
I've considered doing this, but ultimately I don't believe there is value in having a graph displayed with that many nodes and edges, and the better way to reduce the size of the data.json file is to reduce the number of nodes, as that will result in a more understandable graph displayed.
