### ISSUE TITLE
can't get the map.html to load correctly

### ISSUE THREAD

**Issue by Inig0Montoya** [duo-labs/cloudmapper#520]
![Capture1](https://user-images.githubusercontent.com/53946577/62801296-0d7d4c00-baab-11e9-9e6c-0ab50a85a067.PNG)
![Capture2](https://user-images.githubusercontent.com/53946577/62801478-72d13d00-baab-11e9-9ef4-61e7c5e328ed.PNG)

Not sure which step I missed here... or what the details of that error are.

Edit: Also, I ran the prepare command and tried starting the webserver again.

**Comment by 0xdabbad00** [comment]
I'm guessing you loaded `/account-data/map.html` as opposed to `/map.html`.  The `map.html` under `account-data` is used in conjunction with the `iam-report` command.

**Comment by Inig0Montoya** [comment]
Thanks, Scott. What is the correct method for accessing the map.html page if not navigating directly to the URL? If I navigate to just /map.html it returns a 404.

**Comment by 0xdabbad00** [comment]
Oh, I'm sorry, I should have said use `/index.html` . Don't access any file ending in `map.html` directly.  You should be able to run `python cloudmapper.py webserver` and then open `http://127.0.0.1:8000` in your web browser.

**Comment by Inig0Montoya** [comment]
Thank you, this finally loaded after 15 minutes. I understand there are ways of filtering out certain things so I can get a faster load / less clutter.
1. Can I do this after the map has loaded?
2. Also, how do I do this without removing dependencies? My entire goal in trying to use this was to map and understand all of the dependencies across 10+ clients in one of our AWS accounts..

![image](https://user-images.githubusercontent.com/53946577/62804770-dcede000-bab3-11e9-861e-cff881a9066c.png)

**Comment by 0xdabbad00** [comment]
You have to do the filtering at the `prepare` step, or manually edit the `data.json` output file.  Unfortunately, any environments with more than about 20 nodes (which is most environments) is going to be difficult to visualize (as in it is a hard problem universally and not entirely a limitation specifically to CloudMapper).

**Comment by 0xdabbad00** [comment]
I'm closing this as the original issue is resolved.
