### ISSUE TITLE
File iam-get-credential-report.json does not exist

### ISSUE THREAD

**Issue by namtr0** [duo-labs/cloudmapper#529]
When running report after collection I get error about iam-get-credential-report.json not existing or not well-formed.

looked in region folder and the iam-get-credential-report.json does exist
Report works for demo
(I'm only wanting to run anything on us-west-2) I may lack rights on other regions, so other regions do not have the .json above. Would this matter?

```
(cloudmapper) namtr0@user-linux:~/cloudmapper$ python cloudmapper.py report --accounts nonprod
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/home/namtr0/cloudmapper/commands/report.py", line 461, in run
    report(accounts, config, args)
  File "/home/namtr0/cloudmapper/commands/report.py", line 87, in report
    "collection_date": get_collection_date(account)[:10],
  File "/home/namtr0/cloudmapper/shared/common.py", line 335, in get_collection_date
    "File iam-get-credential-report.json does not exist or is not well-formed. Likely cause is you did not run the collect command for this account."
Exception: File iam-get-credential-report.json does not exist or is not well-formed. Likely cause is you did not run the collect command for this account.

```

**Comment by 0xdabbad00** [comment]
CloudMapper is hard-coded to look in the "default" region of the partition for the file.  So for commercial AWS, it will look in the `us-east-1` folder. Do you have the file `iam-get-credential-report.json` in the `us-east-1` folder?

**Comment by namtr0** [comment]
I had set default to us-west-2 in collect.py (replaced all us-east-1 with us-west-2)
Maybe I broke it?
There was no report in any other region so I copied it over to check if that would show and got more errors....it prepares fine but running report yields this now:
`(cloudmapper) namtr0@namtr0-linux:~/cloudmapper$ python cloudmapper.py report --accounts nonprod
* Getting resource counts
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/home/namtr0/cloudmapper/commands/report.py", line 461, in run
    report(accounts, config, args)
  File "/home/namtr0/cloudmapper/commands/report.py", line 97, in report
    account, args.stats_all_resources
  File "/home/namtr0/cloudmapper/shared/common.py", line 297, in get_account_stats
    query_aws(region.account, resource["source"], region),
  File "/home/namtr0/.local/share/virtualenvs/cloudmapper-MIQJXGkq/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
`

**Comment by namtr0** [comment]
I've also generated a report manually and put it in there specifically for us-east-1, still same. I think I either borked it or configured something wrong, but just can't see it cause I'm not learned enough yet.

**Comment by 0xdabbad00** [comment]
I'm going to close this as it's looking like the modifications are making this outside of the scope of what I'm able to support for the project.  CloudMapper assumes that data is collected from all regions, and that global service data (ie. IAM) is collected to us-east-1.  I've never considered what all would break if that were not true.
