### ISSUE TITLE
find_admins finds false admins

### ISSUE THREAD

**Issue by nimrodkor** [duo-labs/cloudmapper#531]
When looking for admins, if the script finds an attached / inline policy which has a statement with the action `*` - it marks the user/role as an admin, even if the resources field of the statement isn't `*` - for exmple a list of s3 buckets.
I think this is a miscunfiguration, but if it is limited to specific resources - it isn't an actual admin.

**Comment by 0xdabbad00** [comment]
The find_admins command is prone to false positives and false negatives (ie. it will identify some principals as admins that are not, and will miss some that are).  It's a hard problem that it makes a best effort on via some simple heuristics.  In your case, you should have received audit findings for a statement like that.  I don't have a good solution to this, other than maybe including a warning somewhere, as solving it to provide correct results all the time would be a much larger undertaking.

**Comment by 0xdabbad00** [comment]
After a quick discussion via DMs elsewhere, I'm closing this as "wont fix" to avoid complicating the code further with exceptions until a better strategy is figured out for more accurately identifying admins.
