### ISSUE TITLE
Option for report and iam_report to iterate over all collected accounts

### ISSUE THREAD

**Issue by TheFlexican** [duo-labs/cloudmapper#533]
Would be an nice feature, if there was an way to run the report and iam_report commands to iterate over all accounts found under ./account-data, then save the results into for example ./web/account-data/[AWS ACCOUNT]/

**Comment by 0xdabbad00** [comment]
The `iam_report` command only supports single accounts at this time.

The other commands support using `--account all` where `all` is a hard-coded keyword that CloudMapper uses to look at all accounts in the `config.json`
