### ISSUE TITLE
Possible to skip collecting data in certain regions?

### ISSUE THREAD

**Issue by stepkirk** [duo-labs/cloudmapper#549]
We have created SCPs to restrict use of certain regions in AWS. Is it possible to tell cloudmapper to collect data for a subset of regions rather than all of them? That would eliminate a lot of calls that fail like so:

```
Making call for account-data/./XXX/ap-northeast-2/ec2-describe-vpn-connections.json
ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeVpnConnections operation: You are not authorized to perform this operation.
```

That same call works for the three AWS regions we allow to be used.

**Comment by 0xdabbad00** [comment]
This is related to #537 (where people have restrictions on their privileges) and also #496 (where a PR was submitted to limit the regions collected from).  As discussed in those, this is currently outside the scope of what I'm able to support as I don't know what all might end up breaking under these circumstances, and they aren't issues I've run into yet myself (although I suspect I will soon, at which point I'll do something about this).  I'm going to close this issue as it duplicates the issue and PR mentioned.  This is more and more becoming a problem I need to tackle.
