### ISSUE TITLE
Unhandled exception during collect

### ISSUE THREAD

**Issue by BritishAirlines** [duo-labs/cloudmapper#564]
Crash during collect stage with unhandled exception: there is no file or directory: 'account-data/./prod/me-south-1/ecs-list-clusters.json'
![1](https://user-images.githubusercontent.com/31643780/65948927-db052500-e443-11e9-93d6-3dc45ff1cdda.jpeg)

**Comment by 0xdabbad00** [comment]
It looks like you don't have the necessary permissions to run CloudMapper.

**Comment by BritishAirlines** [comment]
Hi, it runs well on centos. But ubuntu crashes with this exception. I surely have all the necessary permissions


________________________________
От: Scott Piper <notifications@github.com>
Отправлено: вторник, октября 1, 2019 7:03 PM
Кому: duo-labs/cloudmapper
Копия: Илья Брыков; Author
Тема: Re: [duo-labs/cloudmapper] Unhandled exception during collect (#564)


It looks like you don't have the necessary permissions to run CloudMapper.

**Comment by 0xdabbad00** [comment]
I'm referring to AWS privileges.  I can see in your screenshot the line `authorized to perform ecs:ListClusters on resource: * with an explicit deny` which is saying that an API call was denied because you do not have the necessary privileges.
