### ISSUE TITLE
VPC peering not visible and Deleted resources are still showing in Visualizer. 

### ISSUE THREAD

**Issue by Narayan-PrasadK** [duo-labs/cloudmapper#582]
Thanks in advance.
I have configured config.json and added cidrs for external cirds , when I check my report it is not showing VPC Peering in network visualizer, I'm I missing anything or is this any issue? I'm able to see ec2-describe-vpc-peering-connections.json file in account-data and in that file it contains only
{
"VpcPeeringConnections": []
}
~

Is something is missing? Do I need to do anything to collect data?
And I have found some resource which is not using, so deleted it and again run collect, prepare for my account and checked in network visualizer. still I'm able to see that deleted resource. Do we need to do anything else? Is there any cache concept?

**Comment by 0xdabbad00** [comment]
The VPC peering will only show in the `weboftrust` view.  It will show as a blue line there.

For resources still being there after you deleted them, some ideas:
- Depending on the type of resource, it may take some time for AWS to acknowledge it as being truly gone.
- To be absolutely sure, you could delete (or move) the directory `./account-data/your_account/` . There is not any cache'ing, but I can't think of anything that would cause this.

**Comment by Narayan-PrasadK** [comment]
Thanks.
