### ISSUE TITLE
How can you filter the region for cloudmapper --collect?

### ISSUE THREAD

**Issue by HenryHoggard** [duo-labs/cloudmapper#586]
Looks like there was a previous issue here https://github.com/duo-labs/cloudmapper/issues/304 but it was closed. Was this feature ever implemented?

**Comment by 0xdabbad00** [comment]
There is an open PR for this (#496), but I haven't merged it as I'm not sure what all impact it may have.  I'm going to close this as being a duplicate of that PR.
