### ISSUE TITLE
Need role boundry configured to allow deployment of auditor

### ISSUE THREAD

**Issue by TheFlexican** [duo-labs/cloudmapper#592]
Hi,
Looking for some help. 
I'm not allowed to create roles without specifying a role boundary for the new role. So deployment fails. 

  1/46 | 12:34:21 PM | CREATE_FAILED | AWS::IAM::Role | taskDefinition/TaskRole (taskDefinitionTaskRole3D7BF1E0) API: iam:CreateRole User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/Engineer/XXXXXXXXXXXXX is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXXXXXXXXX:role/CloudmapperauditorStack-taskDefinitionTaskRole3D7B-1D0MLVPEPD877 with an explicit deny

Can you help me out, where and how I can specify the role boundary in the iam policy's in cloudmapperauditor-stack.js ? Tried to find this information on the net, but was not able to find a working solution.

Thank you,

Ralf

**Comment by 0xdabbad00** [comment]
@TheFlexican No IAM role boundary is needed by the auditor itself.  In order to deploy it, you'll need privileges to create the role used by the auditor, which means the ability to create an IAM role and attach policies to it.  Usually this means you have admin privileges to accomplish that.

**Comment by TheFlexican** [comment]
Hi,

I have admin privileges, but when I create a new role, I have to specify a role/permission boundary created by our AWS admins. This role/permission boundary prevents the new role to perform certain actions. Below a snippit of a Cloudformation stack, that creates a new role, where i specify the boundary, maybe this shows you what I mean :)

Resources:
    TheRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: MyRoleName
            MaxSessionDuration: 3600
            PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/role-boundary"
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/SecurityAudit

Thank you!

**Comment by TheFlexican** [comment]
I think i found what the issue is, the cdk deploy command, automatically creates by default an execution role when nothing is specified in ecs.FargateTaskDefinition (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateTaskDefinition.html#executionrole). I need to specify a role boundary to the creation of this role, and that's where i sort of need help with.  

Not sure if this can be done:  https://github.com/aws/aws-cdk/issues/3242

**Comment by TheFlexican** [comment]
I managed to get it working, for executionrole and taskrole to assign a permission boundary with the following code.

    const roleBoundary =  iam.ManagedPolicy.fromManagedPolicyName(this,'roleBoundary', 'role-boundary')

    const executionRole = new iam.Role(this,'executionRole', {
      permissionsBoundary: roleBoundary,
      roleName: 'executionRole',
      assumedBy: new iam.ServicePrincipal('*')
      });

    const taskRole = new iam.Role(this, 'taskRole', {
      permissionsBoundary: roleBoundary,
      roleName: 'roleName',
      assumedBy: new iam.ServicePrincipal('*')
    })
    const taskDefinition = new ecs.FargateTaskDefinition(this, 'taskDefinition', {
      executionRole: executionRole,
      taskRole: taskRole
    });

It will now set the permission boundary, but i ran into a new problems, the other roles it tries to create do not get the permission boundary set, and i see no way of configuring this.

Guess i need to talk to our AWS admins... Thanks.

**Comment by 0xdabbad00** [comment]
If you have a requirement in your environment to set IAM boundaries, that's going to be out of scope for this project to satisfy that environment specific rule.
