### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#6]
Regions and other compound nodes sometimes overlap on top of other structures and there are various other ways in which these look "bad".

For example minimizing regions for some reason often ends up causing one of the worst layouts, where things get spread very far apart vertically.

Some ideas for improvements:
- The bad layouts are largely due to the graphs being too complex, which is due to too many nodes and edges.  To resolve this, we could allow more filtering, and make that easier to do.  Also compress nodes in the initial layout.
- We are using a compound layout to allow nodes (ex. EC2's) to have parent nodes (ex. EC2's are in subnets, which are in AZ's, etc.).  We could allow for non-compound layouts, which would allow us to use algorithms other than cose-bilkent, which may look better.
- Improve cose-bilkent to score and hill climb.  cose-bilkent works by randomly laying out the diagram and then applying spring and gravity forces over iterations to bring things to a state that matches those forces.  This could be improved by making multiple layout attempts and choosing the "best" where a scoring algorithm would need to be created to decide on the "best" layout.  This would need to do things like counting the number of over-lapping edges and nodes, and find the area of the layout (ex. to avoid the layout being too spread out).  Ideally, this scoring would be incorporated into the forces that are applied to bring them toward better states.  Additionally, I think the "final" states are sometimes local maxima and could benefit from some hill climbing techniques to "shake" the state a little on each iteration.

**Comment by 0xdabbad00** [comment]
Nodes can be compressed on the initial layout as shown in this demo: https://rawgit.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/master/demo-compounds-collapsed.html

**Comment by vr00n** [comment]
I also found that for very complex diagrams, where on init - resources are spread across the screen in an exaggerated manner,  clicking the hammer icon aka `redraw with randomized layout` sanitizes the layout to some extent.

**Comment by 0xdabbad00** [comment]
Other than CoSE, another algorithm for compound nodes is elkjs (https://github.com/OpenKieler/elkjs). which is the successor of klay (https://github.com/cytoscape/cytoscape.js-klay).  elkjs has a cytoscape extension https://github.com/jfstephe/cytoscape.js-elk

You can see klay's compound node layout at http://openkieler.github.io/klayjs-d3/examples/interactive/ and clicking "Layer Preserving".

I tried playing around with these, but it didn't work. Unsure if that is because my compound nodes have more than one layer, or I didn't use the right option flags, or what.  This doesn't immediately seem like an easy win though.

**Comment by 0xdabbad00** [comment]
Attempted at a different visualization made in #368 

At this point I believe the best way to improve the layouts is to continue adding ways to reduce the number of nodes shown, such as by filtering by tags that was recently done. I'm therefore closing this.
