### ISSUE TITLE
Assume Roles

### ISSUE THREAD

**Issue by mrxpl0it** [duo-labs/cloudmapper#610]
I want to be able to assume a role in a different account that I do not have an IAM User account for. I typically assume a role in another account.

**Comment by 0xdabbad00** [comment]
It is expected that you will use aws-vault with CloudMapper.  CloudMapper does support a `--profile` flag though otherwise for `collect`.

**Comment by mrxpl0it** [comment]
Thanks for replying. Is that flag in the cloudmapper.py string after the collect command? Like below?

python cloudmapper.py collect --profile xxxxx --config config.json --account xxxxx

**Comment by 0xdabbad00** [comment]
Yes. You can also do `python cloudmapper.py collect --help` and it will display the help for the command.

**Comment by mrxpl0it** [comment]
Thanks for your help and responsiveness!

**Comment by christophetd** [comment]
`aws-vault` will do the trick when using a single account, but what about if you want to collect data about multiple accounts at the same time using `python cloudmapper.py collect --account all`? An approach would be to allow a per-account `profile` attribute in config.json:


```json
{
  "accounts": [
    {
      "id": "1234",
      "name": "account1",
      "default": true,
      "profile": "default"
    },
    {
      "id": "5678",
      "name": "dev",
      "profile": "dev"
    }
...
  ]   
}
```

Then, if you AWS config looks like:

```
[default]
..

[profile dev]
role_arn=xxx
role_session_name=yyy
```

When collecting data of the `dev` account, CloudMapper would assume the role `xxx` before hitting the AWS API. Use-case: AWS organization with multiple children accounts

**Comment by 0xdabbad00** [comment]
I end up writing a simple bash script for this to run `collect` for 100+ accounts.

**Comment by christophetd** [comment]
I would argue it's still an interesting feature to have when getting started with new accounts. Are you open to PR?
