### ISSUE TITLE
report command - auditing accounts - ARN KeyError

### ISSUE THREAD

**Issue by maestretti** [duo-labs/cloudmapper#622]
When I ran `report` I got a few dozen of these errors:
```
* Auditing accounts
WARNING:policyuniverse:ARN Could not parse [AID*******************CS].
WARNING:policyuniverse:Auditor could not parse ARN AID********************CS.
```

Then the report had a critical finding for audit error which detailed as:

```
"exception": "'Arn'",
    "traceback": "Traceback (most recent call last):\n  File \"/cloudmapper/shared/audit.py\", line 1076, in audit\n    audit_iam(findings, region)\n  File \"/cloudmapper/shared/audit.py\", line 210, in audit_iam\n    find_admins_in_account(region, findings)\n  File \"/cloudmapper/shared/iam_audit.py\", line 276, in find_admins_in_account\n    policy[\"Arn\"],\nKeyError: 'Arn'\n"
```
Which flags this line:

https://github.com/duo-labs/cloudmapper/blob/1e60e1fb0bf5ad71d8514c2f5a3a2696b130f4cc/shared/iam_audit.py#L276

I think the error is that the `ARN` is at the next level of JSON up. When `policy` is defined here:

https://github.com/duo-labs/cloudmapper/blob/1e60e1fb0bf5ad71d8514c2f5a3a2696b130f4cc/shared/iam_audit.py#L267

So line 276 should be `role['Arn']` and I think the errors are related but not sure.

**Comment by mdavis332** [comment]
Nice, thanks @maestretti . If I change https://github.com/duo-labs/cloudmapper/blob/1e60e1fb0bf5ad71d8514c2f5a3a2696b130f4cc/shared/iam_audit.py#L276 from `policy` to `role`

and do the same for https://github.com/duo-labs/cloudmapper/blob/1e60e1fb0bf5ad71d8514c2f5a3a2696b130f4cc/shared/iam_audit.py#L458

Then things like `find_admins` start working.

**Comment by kbroughton** [comment]
I can confirm the two changes of mdavi332 fixes the find_admins error.
