### ISSUE TITLE
Source of Public Summary in the webserver's display 

### ISSUE THREAD

**Issue by wjohnston-sfdc** [duo-labs/cloudmapper#632]
Great product! I really enjoy using this to map out our IaaS footprint. My question is around the source IP listed as 0.0.0.0/0 and defined as Public coming from the Cloud. Please see the image i have attached.

Why is cloudmapper defining some external connections coming from specific /32 or /16 addresses and some coming from 0.0.0.0/0?

![Public CloudMappter](https://user-images.githubusercontent.com/50969638/71026744-aefe5500-20be-11ea-8443-2b42a40b8490.png)

**Comment by 0xdabbad00** [comment]
CloudMapper looks at your Security Groups to determine what is allowed access to your resources.  In cases where an unknown CIDR is used, such as a /32 or /16, CloudMapper will create a node for that CIDR.  0.0.0.0/0 is a special case that CloudMapper renames as "Public".

**Comment by wjohnston-sfdc** [comment]
Thank you very much for  the clarification. Closing the issue
