### ISSUE TITLE
python cloudmapper.py prepare --account my-account returns no nodes built

### ISSUE THREAD

**Issue by irontech2020** [duo-labs/cloudmapper#634]
when running the command for prepare after collecting the information with my account returns no nodes built and the map renders empty. 

- 0 nodes built in region eu-north-1
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
- 0 nodes built in region eu-west-1
- 0 nodes built in region ap-northeast-2
- 0 nodes built in region ap-northeast-1
- 0 nodes built in region sa-east-1
- 0 nodes built in region ca-central-1
- 0 nodes built in region ap-southeast-1
- 0 nodes built in region ap-southeast-2
- 0 nodes built in region eu-central-1
- 0 nodes built in region us-east-1
- 0 nodes built in region us-east-2
- 0 nodes built in region us-west-1
- 0 nodes built in region us-west-2
- 0 external CIDRs built
- 0 connections built

**Comment by 0xdabbad00** [comment]
This could be because:
- there are no nodes (ie. you have no EC2s or similar in your account)
- the collect phase ran into problems
- the account name you passed for prepare does not match the name you provided for the collect

**Comment by irontech2020** [comment]
All of these items were double-checked, there are no errors on collect 
Summary: 1072 APIs called. 0 errors
the account has about 50+ instances in it
and the name matches.

**Comment by irontech2020** [comment]
It seems to have been an issue with my credentials profile in the CLI. It seems to be working now.
