### ISSUE TITLE
Error on vanilla install of Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by jeaguilar** [duo-labs/cloudmapper#64]
error: [Errno 2] No such file or directory
  
  ----------------------------------------
  Failed building wheel for pyjq
  Running setup.py clean for pyjq
Failed to build pyjq
Installing collected packages: six, pyjq, netaddr, jmespath, docutils, python-dateutil, botocore, futures, s3transfer, boto3
  Running setup.py install for pyjq ... error

**Fixed** by installing build-essential (sudo apt-get install build-essential)

**Comment by 0xdabbad00** [comment]
Thank you. Resolved in https://github.com/duo-labs/cloudmapper/commit/34e82b4991640d60a01c50fc2438badaa686fac3

**Comment by JulesDT** [comment]
I just downloaded a fresh Ubuntu 16.04.4 LTS Desktop version (You don't specify if it's desktop or server, I assumed Desktop), and build-essential was apparently already installed.

But I found out virtualenv was missing, I did a tiny PR for that

**Comment by jeaguilar** [comment]
For the record, it was 16.04.04 LTS Server.
