### ISSUE TITLE
Add ability to append security group description

### ISSUE THREAD

**Issue by kpawloski** [duo-labs/cloudmapper#66]
This is a feature request more than anything.

It would be great if there was an option to append security group IP descriptions next to their IP address.

It would help when we visually look at a map and say hey what is this IP?

I suppose this would basically be automating the IP definitions in the config.json. (Assuming descriptions exist for those IPs in EC2)

Anyways, wouldn't make sense to enable this by default by an option such as --include-descriptions would be a nice add.

**Comment by 0xdabbad00** [comment]
Currently, you can configure CIDR's in the config file.  I've been thinking about this though, and realized that I should do a couple of things:
1. When doing a `prepare` for any IP that isn't a known CIDR from the config file, display a warning about it.
2. Provide the user with a list of all names used to describe a CIDR from the Security Groups.  I've noticed environments tend to give CIDRs slightly different (or totally different) names in different Security Groups.
3. For known CIDR IPs, I should display a different icon than the icons for unknown CIDRs.  I need to hire someone on fiverr to make me a bunch of icons for that and some other AWS services that don't currently have icons.
4. In the UI, be able to provide more functionality to see info about a CIDR.  This is a bigger problem, where I additionally need to look into using different colors for different ports in the diagrams.

For your issue, I think 1 & 2 would be the easiest to resolve.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
