### ISSUE TITLE
Show service/port on map

### ISSUE THREAD

**Issue by cloudyrion** [duo-labs/cloudmapper#661]
It would be nice if the graph would show service/port number. This would a great help for threat analysis.

**Comment by 0xdabbad00** [comment]
I am no longer continuing development on the network visualization functionality of CloudMapper. I'd be happy to accept a PR though.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
