### ISSUE TITLE
Report generation resulting in process being killed 

### ISSUE THREAD

**Issue by 0xb8000** [duo-labs/cloudmapper#666]
Please mention the following:
- What command was run? python cloudmapper.py report --account my_account
- Are you working out of a pipenv environment, Docker, or something else?
pip env 

this is not the default config. I have added my account ID and subnets in config.json. 
I called the account I am working with my_account.

(cloudmapper) bash-3.2$ python cloudmapper.py report --account my_account
* Getting resource counts
  - my_account
* Getting IAM data
  - my_account
* Getting public resource data
  - my_account
Killed: 9

![Screen Shot 2020-02-24 at 10 28 50 AM](https://user-images.githubusercontent.com/17913340/75176335-31277d00-56f1-11ea-9239-cbf952fc60dd.png)

**Comment by 0xdabbad00** [comment]
Unfortunately, I don't have much of an idea as to why this could be happening and you'll have to figure out what is killing the process.  My best guess CloudMapper might be running out of memory and the OOM is killing it.

**Comment by adam7** [comment]
I saw this issue when running inside docker with only 4GB assigned to the docker vm. Doubling the memory assigned to docker resolved the issue for me.

**Comment by andrewkrug** [comment]
It was the same in my case.  I had to increase the size of my Fargate Container to get a full report to run.  May want to give a little advice on economies of scale in the docs for the auditor.

**Comment by 0xdabbad00** [comment]
I'm closing this due to staleness of the original problem statement and the likelihood that it is memory related, which I've mentioned in #674, to add a way of identifying memory issues.
