### ISSUE TITLE
Feature request: additional visible information, and cropping

### ISSUE THREAD

**Issue by aioue** [duo-labs/cloudmapper#67]
Appending CidrBlocks, and not cropping long names makes the diagram easier to read without having to drill into the details.

### VPCs: add the CidrBlock value in parentheses `()`

![image](https://user-images.githubusercontent.com/1254905/37155011-a92fd1f6-22d9-11e8-8cbe-a20ef498ae02.png)

becomes `dot1 (10.0.0.0/0)`

### Subnets: don't crop subnet names, and append CidrBlock in parentheses

![image](https://user-images.githubusercontent.com/1254905/37155171-193312c4-22da-11e8-8806-13181e0ba3ad.png)

becomes `dot1_private_eu-west-1 (10.0.0.10/20)`

### VPC & Subnets

Add option to show tag (`key:value`) list down left-hand edge of container.

e.g.
```
--------------someVPC----
| tier: edge
| access: public
---------------------------
```

**Comment by 0xdabbad00** [comment]
These are good ideas. 👍Thanks @aioue.   I want to ensure I don't flood the screen with too much text, or end up with nodes that span across a lot of the screen horizontally when not needed.  I may add some preferences ability to the UI to show/hide some of this extra information.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
