### ISSUE TITLE
AccessDeniedException for kms:GetKeyPolicy

### ISSUE THREAD

**Issue by andrewkrug** [duo-labs/cloudmapper#671]
Please mention the following:
- What command was run?
The collect command

- Are you working out of a pipenv environment, Docker, or something else?
Working out of the continuous auditor in Docker + Fargate using cross account roles.

For some accounts with restricted keys the following is logged as an error:
```
kms.get_key_policy({'KeyId': 'xxx', 'PolicyName': 'default'}): An error occurred (AccessDeniedException) when calling the GetKeyPolicy operation: User: arn:aws:sts::xxx:assumed-role/CloudMapper/botocore-session-xxx is not authorized to perform: kms:GetKeyPolicy on resource: arn:aws:kms:us-west-2:xxx:key/xxx
```

I think it should likely be added to the list of KMS AccessDenied exceptions here:https://github.com/duo-labs/cloudmapper/blob/master/commands/collect.py#L150 handled for restricted keys.  If this is true I will PR a fix.

**Comment by andrewkrug** [comment]
The same could likely be said for: `kms.list_grants`

**Comment by 0xdabbad00** [comment]
It'd be great to get a PR for this. Thank you.
