### ISSUE TITLE
Netflix Skunkworks PolicyUniverse WARNING

### ISSUE THREAD

**Issue by andrewkrug** [duo-labs/cloudmapper#672]
During the audit phase of the tool there are a lot of warnings from PolicyUniverse.  

`WARNING:policyuniverse:ARN Could not parse XYZ`

Consider setting this streamLogger for this to critical only for the audit process, iam audit, and iam report.  

If this sounds good I'll drop a PR.

**Comment by 0xdabbad00** [comment]
This is a great idea. I'm not even sure what these warnings mean to be honest, although I've seen them often as well and just ignored them.

**Comment by andrewkrug** [comment]
It just means that the principal in a policy didn't match the regEx for a standard ARN.
