### ISSUE TITLE
Cloudmapper output

### ISSUE THREAD

**Issue by maxi82** [duo-labs/cloudmapper#676]
Hello, I am having some issues with cloudmapper hence wanted some guidance,
command: aws-vault exec admin_dev -- python cloudmapper.py stats --account dev
I get list of output but I would only highlight one thing i.e. S3 buckets that are 10.

Now, when I run this command, aws-vault exec admin_dev aws s3 ls | wc -l
    Output:31
Now, changing profile as I was previously assuming role 
aws-vault exec original account aws s3 ls | wc -l
 Output: 10

May I know, why cloud mapper is unable to see all s3 instances.

Regards,

**Comment by 0xdabbad00** [comment]
My understanding of your situation is:
1. CloudMapper showed 10 s3 buckets in your dev account.
2. aws s3 ls showed 10 s3 buckets in your dev account.
3. aws s3 ls showed 31 s3 buckets in your admin_dev account.

Based on what you said, it sounds like CloudMapper showed the correct number of S3 buckets in your dev account, but that maybe you are expecting it to additionally show the S3 buckets in your admin_dev account?  You would need to tell CloudMapper to look at both your dev and admin_dev accounts for that.

**Comment by 0xdabbad00** [comment]
Closing due to staleness
