### ISSUE TITLE
Regarding reading Metadata in the graph

### ISSUE THREAD

**Issue by kvbamith** [duo-labs/cloudmapper#679]
Hi,
    I have been using cloudmapper for a while to scan the resources in my AWS account. Months back( around Septemeber) I ran cloudmapper through an EC2, and I got a nice graph. I was also able to select any node in the graph and I could see the metadata of the node, but now I use an ECS container to do the same exact thing, but I am unable to see the metadata for a node. Can someone help me understand the cause of this issue? 

Also when I ran up the webserver, a bunch of API calls was generally called, and some files were sent to the web server like data.json and style.json, but now the ECS does not show API's being called, but outputs a graph( again without the ability to see the metadata for a node). Do you think these two issues are related?

The following image is the previous output given when the webserver was called:

![image](https://user-images.githubusercontent.com/26149040/76333503-bc8f3980-62bf-11ea-8d61-96d5e0895dae.png)

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
