### ISSUE TITLE
Regarding filtering by tags

### ISSUE THREAD

**Issue by kvbamith** [duo-labs/cloudmapper#680]
Hi,
    I have been using the Cloudmapper tool for my AWS account for a while. Recently, I have trying to use the feature of filtering by tags, but am not getting the output I expected. When I try to run the prepare script by filtering for a single tag (python3 cloudmapper.py prepare --no-read-replicas --regions us-east-1 --account aws-jdf-apps-devl --config /opt/cloudmapper/src/config.json 0 --tags component:isu ), the cloudmapper tool only recognizes the EC2's that have the exsiting tag and not any other resources like Lambda and S3. 

I have tried changing the **return pyjq.all(".Tags[]", self._json_blob)** lines in nodes.py file to **return pyjq.all(".Tags[]?", self._json_blob)**, but that does not fix my issue. Can someone tell me what I need to do the exisiting code in order to solve my problem?

**Comment by kvbamith** [comment]
Is cloudmapper able to filter ECS and S3 resources by tags? If not, are you guys able to add functionality to enable this filtering? @copumpkin @elliot @marczak @akgood

**Comment by 0xdabbad00** [comment]
@kvbamith I don't think any of the people you tagged are likely to assist you (at least two of them I am certain would not). It is inappropriate to do that.

CloudMapper does not visualize S3 buckets or Lambdas that are not part of VPCs.

**Comment by kvbamith** [comment]
Oh, I apologize for that. I was thinking about the notification system. Thanks for the reply. Does Cloudmapper visualize ECS?

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
