### ISSUE TITLE
Section "details" empty for endpoints

### ISSUE THREAD

**Issue by Alaaguel** [duo-labs/cloudmapper#689]
Hello,
I have managed to install the tool and make it work following all the instructions at following link : https://github.com/duo-labs/cloudmapper#installation

The tool works, I am able to map the AWS account with accuracy but the "details" section is always empty when I click on endpoints.
Do you know where the issue might come from ?

If it's of any use:
- I am working on Ubuntu 18.04.4 (on a fresh VM installed only for cloudmapper)

Thank you in advance !

**Comment by Alaaguel** [comment]
Hello, 
Any idea on this problem?
Thank you in advance.

**Comment by 0xdabbad00** [comment]
I do not know. I've never heard of this issue, so you'll have to debug it on your own.

**Comment by kvbamith** [comment]
Hey!!
     I have been facing the same issue for a long time, and I think I might have figured out the problem. In the prepare.py code file, lines 661-667. The node data is always overwritten with an empty string. When I commented out that entire if statement. I could see the data in the details section. This might be a bug that is already dealt with, but @0xdabbad00 can you please look into this issue?
![image](https://user-images.githubusercontent.com/26149040/82572510-0d39d300-9b4a-11ea-9ec2-49e9122caa36.png)

**Comment by 0xdabbad00** [comment]
Ah, looks like @schosterbarak's PR had changed the default logic: https://github.com/duo-labs/cloudmapper/commit/016bcc0a76378eade0c5f6cf0bb86d1c57ded92c#diff-a491b3e679c964f5b83958cf450f3c2dR789

Looks like that flag just needs to be set to True by default in the code.

**Comment by 0xdabbad00** [comment]
Resolved in #723
