### ISSUE TITLE
Feature request: optional connection visibility

### ISSUE THREAD

**Issue by aioue** [duo-labs/cloudmapper#69]
Using cloudmapper to help unpick a rats nest of systems:

![image](https://user-images.githubusercontent.com/1254905/37162267-bbd451fc-22ec-11e8-8d65-62fe70e214f5.png)

Would like the option of a connectionless view, with instances vaguely grouped near each other inside subnets by name or a tag, etc. e.g.

![image](https://user-images.githubusercontent.com/1254905/37163664-3c339f08-22f0-11e8-98b2-4143297a15a3.png)

(Achieved connection removal locally by leaving source and target empty in `nodes.py` `cytoscape_data`.

Code is very readable.

**Comment by 0xdabbad00** [comment]
You should be able to get a view like this using `--no-internal-edges` in the `prepare` step.  Unfortunately, it won't group by similar tag though.

**Comment by aioue** [comment]
No internal edges works as described.
