### ISSUE TITLE
Ununtu 16.04 ImportError: No module named six.moves.urllib (and other packages)

### ISSUE THREAD

**Issue by jeaguilar** [duo-labs/cloudmapper#70]
On Ubuntu 16.04 Server, ran:
> python cloudmapper.py prepare --config config.production.json  --account production

The following error was returned:
>Traceback (most recent call last):
>  File "cloudmapper.py", line 32, in <module>
>    from cloudmapper.webserver import run_webserver
>  File "/home/juan/cloudmapper/cloudmapper/webserver.py", line 27, in <module>
>    import six.moves.urllib as urllib
>ImportError: No module named six.moves.urllib

Resolved by installing pip:
> sudo apt install python-pip

Then installing six package:
> pip install --user six

Similar issues with other package import errors:
>ImportError: No module named pyjq
>ImportError: No module named netaddr

Resolved with pip as well:
>pip install --user pyjq
>pip install --user netaddr

**Comment by 0xdabbad00** [comment]
Did you run the following yet?
```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by jeaguilar** [comment]
I had but it’s possible I didn’t run that command as sudo.

Thanks!

**Comment by 0xdabbad00** [comment]
You should not it as sudo, that's why you have the `virtualenv` environment.  Learn more at https://virtualenv.pypa.io/en/stable/
