### ISSUE TITLE
Cant filter on tags

### ISSUE THREAD

**Issue by i-robota** [duo-labs/cloudmapper#700]
Running: python cloudmapper.py prepare --account main --tags tagkey=tagvalue
 I'm running this within a venv and it ends up building data with 0 nodes and then erroring out 
(File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)) - presumably because there are no nodes. 
The tag is used though so it should populate some resources - i have tried multiple ways of formatting the command with the same results.

**Comment by 0xdabbad00** [comment]
I'm sorry but I am not able to continue maintaining and supporting the network visualization functionality of CloudMapper.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
