### ISSUE TITLE
Problem displaying ECS resources 

### ISSUE THREAD

**Issue by realshadow** [duo-labs/cloudmapper#702]
Hey,

I am not sure if this is a good place to ask for a bit of help, but here goes... My VPC should, among other things, include:
 - 2 load balancers
 - 2 databases
 - 2 ECS clusters with 2 services and 2 tasks - running on fargate

However - anything related to ECS is not shown. I have checked the account-data folder and everything is there. At first, I thought its an issue with security groups between load balancer and ECS so I have changed the security groups to this:
 - load balancer egress rule only allows traffic to ecs task security group
 - ecs task ingress rule only allows traffic from load balancer security group

Collected, prepared the data again (even removed everything from account-data) and it didnt change anything. I am 100% sure the problem is somewhere on my end. I have tried cloudcraft, cloudviz and lucidchart as an alternative just to see if they would work and they have the same problem. Some of them do not support fargate afaik.

Is there something else I can do?

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
