### ISSUE TITLE
Support adding notes to objects in mapview

### ISSUE THREAD

**Issue by d3c1978** [duo-labs/cloudmapper#709]
As a user, it would be of great help if there is an option to enter notes for an object that can be stored as a tag (add new, edit existing) if the user has appropriate permissions.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
