### ISSUE TITLE
Create a Filter "--Public-Connection" (0.0.0.0/0 + PublicIP) 

### ISSUE THREAD

**Issue by Lucas-L-Alcantara** [duo-labs/cloudmapper#71]
Create a Filter "--Public-Connection" (0.0.0.0/0 + PublicIP) 

How can i get just public instances ? Web server keep showing instances with no public connection when  "--no-internal-edges" is used .

Another great filter to be create is "--instance-name" in "ghaterer.py" script. Sometimes we need specific information about 1 instance and neighbors.

thnks

**Comment by 0xdabbad00** [comment]
The `--no-internal-edges` flag just doesn't show the edges, but will still display all of the internal nodes.  It sounds you're interested in seeing only the nodes that are publicly exposed?

As for the second request, I'll look into how that might best be accomplished.

**Comment by Lucas-CyberSec** [comment]
It sounds you're interested in seeing only the nodes that are publicly exposed?
YEAH! This would be perfect for security analysis. Thks

**Comment by 0xdabbad00** [comment]
Some of original ideas in this issue still haven't been worked on, but the `public` command can identify all of the publicly exposed resources.

**Comment by 0xdabbad00** [comment]
Closing this as I believe the main goal is accomplished by the `public` command.
