### ISSUE TITLE
Read from cached file again

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#718]
In #669 I apparently commented out functionality I should not have:
https://github.com/0xdabbad00/cloudmapper/blob/23a9fbec5c3c39b604af3817cabaacd5605dbbe6/shared/public.py#L74

Uncomment that

**Comment by w0rmr1d3r** [comment]
Fixed that in this PR https://github.com/duo-labs/cloudmapper/pull/853
