### ISSUE TITLE
eks:describe-cluster failures

### ISSUE THREAD

**Issue by acdha** [duo-labs/cloudmapper#729]
Running collect using master (e611d2a05b462c33abb570bed2b1aae491b49fe0) gets this error in every region:

```
* Getting eks:describe-cluster info
  Making call for account-data/./aws-bard-development/eu-north-1/eks-describe-cluster.json
Exception: Parameter validation failed:
Missing required parameter in input: "name"
```

**Comment by 0xdabbad00** [comment]
Looks like I forgot to do a `list-clusters` then `describe-cluster` with the values from that here: https://github.com/duo-labs/cloudmapper/blob/e611d2a05b462c33abb570bed2b1aae491b49fe0/collect_commands.yaml#L351

Currently, CloudMapper does not do anything with the info collected there. So you can comment out those lines in the `collect_commands.yaml` file as an interim fix.

**Comment by acdha** [comment]
Oh, that's a really nice mechanism for this — it made a patch trivial.

**Comment by falconws** [comment]
Affected me too.
Why this PR closed without merge to master branch?
I apply this patch, my collect process made `0 errors`.

**Comment by 0xdabbad00** [comment]
Hmm, I think what happened is 14 days ago I renamed the `master` branch to `main` in light of current societal issues being raised, and deleted the `master` branch.   I think in doing so it somehow resulted in closing the PR.  I don't think I can revive the PR, so I'll create a new PR myself unless @acdha wants to ensure he gets in the commit history by recreating a PR.

**Comment by acdha** [comment]
@0xdabbad00 I cherry-picked #742 for this in case you haven't already done so

**Comment by 0xdabbad00** [comment]
Merged. Thank you @acdha !

**Comment by acdha** [comment]
That was impressively fast – thanks!
