### ISSUE TITLE
Update links to screenshots in README.md

### ISSUE THREAD

**Issue by gchib297** [duo-labs/cloudmapper#737]
The links to images in README.md [Screenshots](https://github.com/duo-labs/cloudmapper#screenshots) section are broken.
A minor change is required in the src url, replace the branch name **master** with **main**. For example:
Change 
`<img src="https://raw.githubusercontent.com/duo-labs/cloudmapper/master/docs/images/ideal_layout.png" width=100% alt="Ideal layout">` to
`<img src="https://raw.githubusercontent.com/duo-labs/cloudmapper/main/docs/images/ideal_layout.png" width=100% alt="Ideal layout">`

**Comment by 0xdabbad00** [comment]
Thank you for spotting this @gchib297 and identifying the fix. I've sent in a PR to resolve this.
