### ISSUE TITLE
prepare step returns 0 nodes built, 0 external CIDRs built, 0 connections built

### ISSUE THREAD

**Issue by falconws** [duo-labs/cloudmapper#740]
This is similar #634 .

My config.json is

```
cat config.json
{
    "accounts": [
        {
            "default": true,
            "id": "NNNNNNNNNN",
            "name": "production"
        }
    ],
    "cidrs":
    {}
}
```

I'm using us-west-2 region only, so I ran collect command below

```
python cloudmapper.py collect --clean --regions us-west-2 --account production
```

Result is

```
--------------------------------------------------------------------
Summary: 169 APIs called. 0 errors
```

Note: #729 patched because an error occurs.

Then

```
python cloudmapper.py prepare --account production
Building data for account production (936540236307)
- 0 nodes built in region us-east-1
- 0 nodes built in region us-west-2
- 0 external CIDRs built
- 0 connections built
```

And

```
python cloudmapper.py webserver --public
```

Access http://localhost:8000/ , show me **empty** circle graph only.

Am I wrong?
Please help me.

**Comment by falconws** [comment]
Does @0xdabbad00 or anyone help?
I'm in real trouble.

**Comment by 0xdabbad00** [comment]
The network visualization capabilities of CloudMapper are no longer maintained.
I would review the data collected to ensure it actually has resources.

**Comment by falconws** [comment]
@0xdabbad00 
Thank you for your response.
I'm waiting for solve this issue.

By the way, this issue isn't solved.
Why are you closed this issue?

**Comment by 0xdabbad00** [comment]
The issue is closed because this functionality is no longer maintained.

**Comment by aSapien** [comment]
Same issue here. Would've been nice if `unmaintained_functionality` was mentioned in docs. It would've save me a few hours.
