### ISSUE TITLE
Cloudmapper authentication

### ISSUE THREAD

**Issue by messi26** [duo-labs/cloudmapper#741]
While setting up cloudmapper, can the initial authentication be done without providing access keys and just on the basis of IAM roles?

**Comment by 0xdabbad00** [comment]
Yes, CloudMapper uses the AWS SDK, so you never provide CloudMapper with access keys. It uses the methods provided by the SDK, which include accessing `~/.aws/config`, your environment variables (which get set by aws-vault), the EC2 metadata service, ECS, etc.
