### ISSUE TITLE
flag to prepare that accepts subfolder

### ISSUE THREAD

**Issue by mroe1234** [duo-labs/cloudmapper#764]
When managing multiple accounts, I can understand why you don't want to graph multiple accounts at once, however it would be nice to be able to create a directory structure within the web directory so that each account can be viewed.  At the moment.  To keep things easier maybe also add a directory flag to the web server command so each account can be kept separate.

something like:

`python cloudmapper.py prepare --account foo --dir foo; python cloudmapper.py webserver --dir foo --port 8001
python cloudmapper.py prepare --account bar --dir bar; python cloudmapper.py webserver --dir bar --port 8002
python cloudmapper.py prepare --account baz --dir baz; python cloudmapper.py webserver --dir baz --port 8003
`

Then apache/nginx can handle the rewrite as you wish. So /cloudmapper/foo -> 127.0.0.1:8001 and /cloudmapper/bar -> 127.0.0.1:8002, etc.

**Comment by 0xdabbad00** [comment]
The network visualization functionality of this project is no longer being maintained. As such I'm closing this issue.
