### ISSUE TITLE
Network map

### ISSUE THREAD

**Issue by JohnMops** [duo-labs/cloudmapper#789]
Please mention the following:
- What command was run?:

Followed the guide and i do not see the network map getting created

- Are you working out of a virtualenv environment, Docker, or something else?

macos virtual env 

Contents
Account Summary
Accounts reviewed
Resources
Resource counts
Region usage
IAM
Public network resources
Counts of public resources by type
Counts of public resources by port ranges
Findings Summary
Counts of finding types by account
Links to findings
Counts of findings by account
Findings

This is what i have after starting the server 
Am i doing something wrong?

**Comment by 0xdabbad00** [comment]
Looks like you're browsing a different page than you intended. The network map is at `/index.html` and it looks like you're looking at the report at `/account-data/report.html`

**Comment by JohnMops** [comment]
@0xdabbad00 Thank you very much ! I knew I did something wrong.
