### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by adespain** [duo-labs/cloudmapper#80]
When I run this on docker I get this error:
`cloudmapper.py: error: argument --account-name: expected one argument`

Am I doing something wrong?

**Comment by adespain** [comment]
nevermind I see documentation needs to be updated to change accountname to account maybe?

**Comment by adespain** [comment]
yeah the README still says to use accountname, account needs to be used instead.

**Comment by 0xdabbad00** [comment]
Thank you for identifying these.  I'm currently working on a number of updates that will make CloudMapper work with multiple accounts so this will be changed to `--accounts` .

**Comment by 0xdabbad00** [comment]
I fixed the naming issues in #115, but also in doing so I've decided to drop support for Docker as it is not being maintained.

**Comment by sebastientaggart** [comment]
Just in case anyone is looking for Docker support (as I was when I stumbled on this thread), I've written up support here: https://github.com/sebastientaggart/docker-cloudmapper

**Comment by landsman** [comment]
This is sad. If project had docker I can run it after 5 minutes. Now I am installing python stuffs for 30 minutes. This is the reason. Or I would be able to run it on development server easily, sandboxed.
