### ISSUE TITLE
[Question] no map created for one out of three accounts

### ISSUE THREAD

**Issue by sonofagl1tch** [duo-labs/cloudmapper#801]
Please mention the following:
# What command was run?
```
python cloudmapper.py collect --account test
python cloudmapper.py report --account  test
python cloudmapper.py prepare --account test
python cloudmapper.py webserver
```

# Are you working out of a virtualenv environment, Docker, or something else?
- running out of avirtualenv on an EC2 instance.

# background
I have 3 aws accounts I have used cloudmapper on. the first 2 collected the data as expected and displayed maps generated from the data. However, the third account only shows up as a single circle on the map. I can see that nodes were found via the collection script when I output the stats of the account but when I run a prepare i see 0's across the board. I am assuming there is no map because the prepare statement would show values if there was information to display. How can I further troubleshoot why this single account is not mapping? Thanks!

# command outputs
## stats output
- S3 buckets              24
- EC2 instances           0
- ELBs                    0
- ELBv2s                  0
- RDS instances           0
- Redshift clusters       0
- ElasticSearch domains   0
- Elasticache clusters    0
- SNS topics              0
- SQS queues              0
- CloudFronts             16
- Autoscaling groups      0
- ElasticBeanstalks       1
- Firehose streams        0
- Glacier vaults          0
- KMS keys                6
- Lambda functions        22
- Glue Jobs               0
- Glue Triggers           0
- Image saved to resource_stats.png

## prepare output
- 0 nodes built in region eu-north-1
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
- 0 nodes built in region eu-west-1
- 0 nodes built in region ap-northeast-2
- 0 nodes built in region ap-northeast-1
- 0 nodes built in region sa-east-1
- 0 nodes built in region ca-central-1
- 0 nodes built in region ap-southeast-1
- 0 nodes built in region ap-southeast-2
- 0 nodes built in region eu-central-1
- 0 nodes built in region us-east-1
- 0 nodes built in region us-east-2
- 0 nodes built in region us-west-1
- 0 nodes built in region us-west-2
- 0 external CIDRs built
- 0 connections built

**Comment by 0xdabbad00** [comment]
The network visualization functionality of CloudMapper is no longer maintained. 

Looking at the output there though, that account does not have any resources that are visualized by that functionality. It only shows resources that have Security Groups, and none of those resources do.
