### ISSUE TITLE
Declare the network visualization functionality is no longer maintained

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#802]
- Update the issue template to mention this
- Mention it in the readme
- Mention it when someone runs prepare

**Comment by cdowey-r7** [comment]
I was looking forward to seeing it all visualized after it spent an hour collecting all the data... so disappointed!

**Comment by w0rmr1d3r** [comment]
Updating the documentation here -> https://github.com/duo-labs/cloudmapper/pull/854
@cdowey-r7 @0xdabbad00

**Comment by w0rmr1d3r** [comment]
I believe we can close this now @0xdabbad00 .
Cheers!
