### ISSUE TITLE
Put account data into a single account_data directory

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#81]
Currently, when you gather data about an account, CloudMapper puts this in a directory named after the account, such as `./prod` .  Eventually, someone is going to fork CloudMapper and commit all of their account data up to Github, so we should avoid that.  To avoid that, and to better organize the CloudMapper directory, I'll create an `account_data` directory where all account data will go.  I'll then add that to the `.gitignore` file so people won't accidentally upload that data.

**Comment by dserodio** [comment]
I believe this was already done: the gathered data is currently under a subdirectory of `account_data`, and `account_data` is in .gitignore

**Comment by 0xdabbad00** [comment]
Correct. I did fix this, and forgot to close the ticket. I implemented this at some point in the past two weeks.
