### ISSUE TITLE
browsers unable to render large environments

### ISSUE THREAD

**Issue by Viss** [duo-labs/cloudmapper#83]
I'm working on a customers network, and this customer doesn't have any network diagrams. To fix this, I thought a good start would be to run cloudmapper on their AWS infrastructure. 

They have 840 or so ec2 instances, and 90+ externally available cidrs. Even when I use the group-by-tag options and try to reduce the edge count, (it was ~250,000 originally, i got it down to ~43,000) when attempting to load the results in a browser, nothing ever renders.

Is there a better way to group large environments, or is there possibly a way to render things out to an image instead of letting a browser interact with a canvas that lets the user move elements around?

or barring that, is there another tool similar to cloudmapper but that works on large environments?

**Comment by Viss** [comment]
Yep, you hit the nail on the head.
I guess my answer is to just wait?

I managed to get the thing to load, its reeeeeeeeally slow though.

I wonder if it would be worth adding a feature surrounding doing mapping by network architecture? like, by subnet, versus by individual host inside ec2?

from a 10,000 foot view, that alone would produce a heaps of useful data. I'll admit I have not yet looked at all the open feature requests and issues to see if anyone else has already suggested something similar..

**Comment by 0xdabbad00** [comment]
One of the ideas in #6 is to compress the compounds nodes (ex. subnets) to single nodes, which would help a lot.  I'm going to close this as the issues seem to be covered elsewhere.  There is a fair bit of work that has yet to be done on CloudMapper for larger environments.
