### ISSUE TITLE
Failure iam.amazonaws.com

### ISSUE THREAD

**Issue by flex2000** [duo-labs/cloudmapper#833]
Hello ,

tried the cloudmapper already with different Linux distributions but get everytime 
Failures:
  iam.get_account_authorization_details({}): Connection was closed before we received a valid response from endpoint URL: "https://iam.amazonaws.com/".
root@2a04454fd49a:/opt/cloudmapper# 

==>Found the solution. The permission mentioned are not enough.

**Comment by flex2000** [comment]
if I try the report anyway afterwards I get:

root@2a04454fd49a:/opt/cloudmapper# python cloudmapper.py report --account Training
* Getting resource counts
  - Training
* Getting IAM data
  - Training
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/opt/cloudmapper/commands/report.py", line 471, in run
    report(accounts, config, args)
  File "/opt/cloudmapper/commands/report.py", line 228, in report
    account_stats = get_access_advisor_active_counts(account, args.max_age)
  File "/opt/cloudmapper/shared/common.py", line 378, in get_access_advisor_active_counts
    *json_account_auth_details["UserDetailList"],
KeyError: 'UserDetailList'
root@2a04454fd49a:/opt/cloudmapper#

**Comment by 0xdabbad00** [comment]
For the first issue, it looks like your internet connection was broken.
For the second issue, nothing will work if you can't get the IAM data.
