### ISSUE TITLE
Add checks for more deprecated policies

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudmapper#834]
AWSLambdaFullAccess -> AWSLambda_FullAccess
AWSLambdaReadOnlyAccess -> AWSLambda_ReadOnlyAccess

**Comment by w0rmr1d3r** [comment]
Shall we add them here @0xdabbad00 ?
https://github.com/duo-labs/cloudmapper/blob/bebf0d1a8f785b5d99995a9f120426b6ab3df4ee/shared/iam_audit.py#L19

**Comment by w0rmr1d3r** [comment]
This has a PR https://github.com/duo-labs/cloudmapper/pull/851 🎉
