### ISSUE TITLE
README Getting Started instructions a little poor

### ISSUE THREAD

**Issue by partoneoftwo** [duo-labs/cloudmapper#836]
The README file was missing key information which was not evident to me. It assumes implicit knowledge of AWS Commandline tooling.

In fact when I gave up on getting Cloudmapper to work, and moved on to Prowler for my auditing needs I managed to fill in the blanks. The Prowler Getting Started documentation,located here, https://github.com/toniblyx/prowler ,  states that you must define AWS Secrets using the AWS CLI.
This is not explicitly and properly written in the Cloudmapper documentation. I was searching for a place to store the API key and secret into the config.json, but to no avail (naturally). I understand that Cloudmapper uses the AWS CLI extensively and this is the reason why AWS CLI handles the secret. However it is not easy to derive this knowledge out of thin air.

**Comment by 0xdabbad00** [comment]
Thank you. Unfortunately CloudMapper is not focused on the same audience as prowler is. I do assume a more technical and experienced user base.
