### ISSUE TITLE
Optimize for large accounts

### ISSUE THREAD

**Issue by hb3b** [duo-labs/cloudmapper#84]
Cloudmapper's UI struggles quite a bit with large accounts. Panning is laggy on diagrams backed by 50+ megabyte data files. I imagine it would be a huge undertaking to optimize the storage system and UI for data files like ours.

This isn't so much a request for work to be done but more of an FYI that we'd appreciate any upcoming performance fixes. Thanks for the hard work and polished product.

**Comment by 0xdabbad00** [comment]
Similar concerns were raised recently in #83.  I haven't experimented with it, but I assume that the size of the data files (50MB) shouldn't be a problem for most users I expect to use the tool.  I believe it's not the file size that is the problem, but the number of items displayed (which happens to be correlated to the file size).  For example, I don't think it would make much difference if the storage system stored each resource in 1KB versus 10MB.  If you have 10 resources displayed it will do fine no matter what the underlying storage is, and if you have 1000 resources, it will be unresponsive.   My general belief is that I shouldn't get too worried about the file size until it starts exceeding 1GB.  There are definitely ways of reducing the file size though if this is a problem area.

I don't have much time to do a lot of development on the tool for a while, but I think the biggest wins are going to be around collapsing compound nodes (ex. subnets) to single nodes, so you don't see all of the leaf nodes that are the EC2's, RDS, etc.  I think that will have the biggest benefits in both terms of making the diagrams more understandable, and also improve the performance of their layout and interaction.

**Comment by hb3b** [comment]
Thank you @0xdabbad00. I somehow missed #83.
