### ISSUE TITLE
icons do not appear on the webpage

### ISSUE THREAD

**Issue by alanxavier** [duo-labs/cloudmapper#86]
I did an install of cloudMapper, when displaying a web page does not appear the icons. ex: ec2, rds
![image](https://user-images.githubusercontent.com/25588902/40077157-25705ddc-5857-11e8-9b07-879dc6029413.png)

**Comment by 0xdabbad00** [comment]
Closing as duplicate of #19 . This is normally resolved simply by refreshing the page.  It's unknown still why this happens.

**Comment by alanxavier** [comment]
I used nginx and it worked perfectly, thanks.

Good project congratulations.
