### ISSUE TITLE
Connection details only available at startup

### ISSUE THREAD

**Issue by coryk2049** [duo-labs/cloudmapper#87]
It looks like the connection (source / target) details (including security group id, port range) between nodes is only available when you first start cloudmapper. Once you collapse two linked nodes and then expand, the connection details are no longer available even when you click on the connection links between nodes.
Please let us know if this behavior is a known issue, and will there be a possible fix for it. Cheers!

**Comment by 0xdabbad00** [comment]
I hadn't noticed this before.  I'll look into it.

**Comment by 0xdabbad00** [comment]
Looks like I need to reassociate the action for when an edge is clicked on after any expand or collapse.  This code is at https://github.com/duo-labs/cloudmapper/blob/437dd11207a2122836470a7698f83641b662e433/web/js/cloudmap.js#L307

I'll make the fix next week.

**Comment by 0xdabbad00** [comment]
Finally got around to this.  Fixed in #116
