### ISSUE TITLE
Network Mapping - EC2 Classic

### ISSUE THREAD

**Issue by astrumas** [duo-labs/cloudmapper#870]
I am looking to use this tool to map out our current EC2 Classic infrastructure to be used to help with planning our migration out of Classic.

I see that audit results reference classic, but the network diagram appears to exclude EC2 instances that are in EC2 classic.

Is there anyway I can include these resources in the map?

**Comment by 0xdabbad00** [comment]
The network mapping functionality is no longer maintained.

**Comment by w0rmr1d3r** [comment]
@0xdabbad00 is there someplace documented that the network mapping functionality is no longer maintained?
