### ISSUE TITLE
Feature: Add AWS VPN Gateway and Connections

### ISSUE THREAD

**Issue by bryantcj52** [duo-labs/cloudmapper#88]
We have a few AWS VPN connections to external data centers and it would be nice to see the gateway IP and which VPCs have VPN connections to that gateway. All of our traffic is outbound over the vpn and not inbound so the normal process of Security Group rules showing connections doesn't work for this use case.

**Comment by 0xdabbad00** [comment]
I'm closing this issue as the network diagram functionality of CloudMapper is no longer being maintained.  Other features of CloudMapper, such as the audit functionality, is still maintained. If someone is interested in maintaining the network diagram functionality they can look at the issues tagged `unmaintained_functionality` for all the issues related to this that have been closed as they will unfortunately not be worked on by me.
