### ISSUE TITLE
Collect single region

### ISSUE THREAD

**Issue by nsu700** [duo-labs/cloudmapper#886]
I am an organisation user of AWS, however the command `python cloudmapper.py collect --account $MYACCOUNT` will scan across all of the regions, how can I specific it to scan only one region please?

Or can I limit it to scan only the resource created under my account, thank you

**Comment by Lusitaniae** [comment]
please do this, no point spending hours scanning all regions when most accounts will use only one or two

**Comment by ankurloriya** [comment]
Found this flag from document
`--regions 'us-south-1,us-north-1'`

**Comment by MathRig** [comment]
Hi, 

I tried the --regions option but is continue to scan the default us region. 
Is there a way to add the default region to a config file ?

Thanks. 
Math.

**Comment by 0xdabbad00** [comment]
The default region is always collected as it is needed for the global services (ex. IAM) and I didn't break out functionality to only collect the global services there.
