### ISSUE TITLE
Remove connections from mapping

### ISSUE THREAD

**Issue by AlisonIsidro** [duo-labs/cloudmapper#913]
Hello, how is everything ? I'm using cloudmapper in a project and I would like to know if there is a way to disable the web mapping connections, so that only the icons remain

**Comment by caseybecking** [comment]
You can turn the opacity of the lines to 0.0 in the style.json, this will make them invisible, this does not remove them but hides them from the view, not sure if that helps you or not?

**Comment by 0xdabbad00** [comment]
The network visualization is no longer being maintained.
